const pool = require('../config/database');

const universities = [

  // ══════════════════════════════════════════════════════════════
  // FRANCE — 10 universités
  // ══════════════════════════════════════════════════════════════
  {
    nom: 'Université Paris-Saclay',
    pays: 'France', ville: 'Gif-sur-Yvette', code_pays: 'fr',
    type: 'publique',
    domaines: ['Sciences', 'Ingénierie', 'Médecine', 'Droit', 'Économie'],
    niveaux: ['Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 28,
    frais_scolarite: '243 €/an (droits nationaux)',
    frais_inscription: '92 €/an (CVEC inclus)',
    moyenne_requise: 14.00,
    classement_mondial: 15, classement_national: 1,
    description: 'Meilleure université française selon le classement mondial QS 2024. Forte en sciences, ingénierie et médecine. Campus de 48 000 étudiants.',
    points_forts: ['#1 France QS 2024', 'Fort réseau recherche', 'Nombreux labos d\'excellence', 'Proximité Paris'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'CV', 'Lettre de motivation', 'Passeport', 'TCF/DELF B2 minimum'],
    plateforme: 'Campus France',
    cout_plateforme: '50 € (frais Campus France)',
    lien_candidature: 'https://www.universite-paris-saclay.fr/formation/candidature',
    lien_officiel: 'https://www.universite-paris-saclay.fr',
    date_ouverture: '2024-12-01', date_cloture: '2025-03-31',
  },
  {
    nom: 'Sorbonne Université',
    pays: 'France', ville: 'Paris', code_pays: 'fr',
    type: 'publique',
    domaines: ['Lettres', 'Sciences', 'Médecine', 'Sciences humaines'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 32,
    frais_scolarite: '243 €/an',
    frais_inscription: '92 €/an',
    moyenne_requise: 13.50,
    classement_mondial: 59, classement_national: 3,
    description: 'L\'une des universités les plus anciennes du monde (1257). Excellence en médecine, lettres et sciences. Au cœur de Paris.',
    points_forts: ['Top 60 mondial', 'Médecine réputée', 'Réseau alumni puissant', 'Centre de Paris'],
    documents_requis: ['Relevés de notes L1-L3', 'Diplôme apostillé', 'CV', 'Lettre de motivation', 'Passeport', 'DELF/DALF B2'],
    plateforme: 'Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://candidature.sorbonne-universite.fr',
    lien_officiel: 'https://www.sorbonne-universite.fr',
    date_ouverture: '2024-12-01', date_cloture: '2025-03-15',
  },
  {
    nom: 'Université Claude Bernard Lyon 1',
    pays: 'France', ville: 'Lyon', code_pays: 'fr',
    type: 'publique',
    domaines: ['Sciences', 'Santé', 'Ingénierie', 'Sport'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 38,
    frais_scolarite: '243 €/an',
    frais_inscription: '92 €/an',
    moyenne_requise: 13.00,
    classement_mondial: 371, classement_national: 8,
    description: 'Spécialisée en sciences, santé et ingénierie. Lyon est la 2ème ville étudiante de France, très appréciée des étudiants africains.',
    points_forts: ['Fort en médecine/pharmacie', 'Vie étudiante dynamique', 'Coût de vie modéré vs Paris', 'Bon taux d\'insertion'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'CV', 'Passeport', 'DELF B2'],
    plateforme: 'Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://www.univ-lyon1.fr/formation/candidature-internationale',
    lien_officiel: 'https://www.univ-lyon1.fr',
    date_ouverture: '2024-11-15', date_cloture: '2025-03-31',
  },
  {
    nom: 'Université Grenoble Alpes',
    pays: 'France', ville: 'Grenoble', code_pays: 'fr',
    type: 'publique',
    domaines: ['Ingénierie', 'Sciences', 'Informatique', 'Économie', 'Droit'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 40,
    frais_scolarite: '243 €/an',
    frais_inscription: '92 €/an',
    moyenne_requise: 13.00,
    classement_mondial: 312, classement_national: 6,
    description: 'Excellente en ingénierie et informatique. Grenoble est une ville technologique (STMicroelectronics, Schneider, Soitec). Idéale pour les profils scientifiques.',
    points_forts: ['Forte en tech/ingé', 'Partenariats industrie', 'Coût vie modéré', 'Cadre alpin'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'CV', 'Lettre de motivation', 'DELF B2'],
    plateforme: 'Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://international.univ-grenoble-alpes.fr/candidater',
    lien_officiel: 'https://www.univ-grenoble-alpes.fr',
    date_ouverture: '2024-11-15', date_cloture: '2025-03-31',
  },
  {
    nom: 'Sciences Po Paris',
    pays: 'France', ville: 'Paris', code_pays: 'fr',
    type: 'grande_ecole',
    domaines: ['Sciences politiques', 'Économie', 'Droit', 'Relations internationales', 'Sociologie'],
    niveaux: ['Master'],
    langue: 'Français/Anglais', niveau_langue: 'C1',
    taux_admission: 12,
    frais_scolarite: '0 - 19 080 €/an (selon revenus)',
    frais_inscription: '0 €',
    moyenne_requise: 15.00,
    classement_mondial: 219, classement_national: 2,
    description: 'Grande école de référence en sciences humaines. Formation d\'élite pour les futurs diplomates, hauts fonctionnaires et dirigeants. Système de bourses étendu.',
    points_forts: ['Réseau alumni exceptionnel', 'Modulation des frais selon revenus', 'Formation bilingue', 'Stage obligatoire'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'CV', 'Lettre de motivation détaillée', 'Lettres de recommandation (x2)', 'DELF C1 ou IELTS 7.0', 'Passeport'],
    plateforme: 'Directe (site Sciences Po)',
    cout_plateforme: '0 €',
    lien_candidature: 'https://www.sciencespo.fr/admissions/fr.html',
    lien_officiel: 'https://www.sciencespo.fr',
    date_ouverture: '2024-11-01', date_cloture: '2025-01-15',
  },
  {
    nom: 'Université de Bordeaux',
    pays: 'France', ville: 'Bordeaux', code_pays: 'fr',
    type: 'publique',
    domaines: ['Droit', 'Économie', 'Sciences', 'Santé', 'Psychologie'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 42,
    frais_scolarite: '243 €/an',
    frais_inscription: '92 €/an',
    moyenne_requise: 12.50,
    classement_mondial: 501, classement_national: 10,
    description: 'Université complète avec une forte tradition en droit, économie et sciences de la vie. Bordeaux est une ville agréable avec un coût de vie raisonnable.',
    points_forts: ['Droit et économie reconnus', 'Bonne qualité de vie', 'Accueil international fort', 'Réseau alumni actif'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'CV', 'DELF B2'],
    plateforme: 'Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://www.u-bordeaux.fr/international/venir-etudier-a-bordeaux',
    lien_officiel: 'https://www.u-bordeaux.fr',
    date_ouverture: '2024-11-15', date_cloture: '2025-03-31',
  },
  {
    nom: 'Université de Montpellier',
    pays: 'France', ville: 'Montpellier', code_pays: 'fr',
    type: 'publique',
    domaines: ['Médecine', 'Droit', 'Sciences', 'Pharmacie'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 44,
    frais_scolarite: '243 €/an',
    frais_inscription: '92 €/an',
    moyenne_requise: 12.50,
    classement_mondial: 601, classement_national: 12,
    description: 'Doyenne des universités francophones (1289). Forte en médecine et droit. Ville ensoleillée et dynamique, très appréciée des étudiants africains.',
    points_forts: ['Faculté de médecine historique', 'Très bon accueil international', 'Ville agréable', 'Prix du logement modéré'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'Lettre de motivation', 'CV', 'DELF B2'],
    plateforme: 'Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://www.umontpellier.fr/formations/candidater',
    lien_officiel: 'https://www.umontpellier.fr',
    date_ouverture: '2024-11-15', date_cloture: '2025-03-31',
  },
  {
    nom: 'Université Toulouse III - Paul Sabatier',
    pays: 'France', ville: 'Toulouse', code_pays: 'fr',
    type: 'publique',
    domaines: ['Aéronautique', 'Ingénierie', 'Sciences', 'Informatique', 'Santé'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 40,
    frais_scolarite: '243 €/an',
    frais_inscription: '92 €/an',
    moyenne_requise: 13.00,
    classement_mondial: 651, classement_national: 13,
    description: 'Au cœur de la "Silicon Valley européenne". Airbus, Thales, Safran sont à Toulouse. Formation d\'excellence en aéronautique et ingénierie.',
    points_forts: ['Aéronautique/aérospatial #1 France', 'Partenariats Airbus/Thales', 'Débouchés excellents', 'Ville jeune et festive'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'CV', 'DELF B2'],
    plateforme: 'Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://www.univ-tlse3.fr/international',
    lien_officiel: 'https://www.univ-tlse3.fr',
    date_ouverture: '2024-11-15', date_cloture: '2025-03-31',
  },
  {
    nom: 'Université de Strasbourg',
    pays: 'France', ville: 'Strasbourg', code_pays: 'fr',
    type: 'publique',
    domaines: ['Droit', 'Sciences', 'Médecine', 'Lettres', 'Chimie'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 42,
    frais_scolarite: '243 €/an',
    frais_inscription: '92 €/an',
    moyenne_requise: 13.00,
    classement_mondial: 201, classement_national: 5,
    description: 'Très bien classée, frontalière avec l\'Allemagne. 18 Prix Nobel parmi ses anciens. Forte en chimie, droit européen et sciences.',
    points_forts: ['18 Prix Nobel', 'Droit européen unique', 'Double diplôme franco-allemand possible', 'Ville européenne'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'Lettre de motivation', 'CV', 'DELF B2'],
    plateforme: 'Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://www.unistra.fr/internationale/candidature',
    lien_officiel: 'https://www.unistra.fr',
    date_ouverture: '2024-11-15', date_cloture: '2025-03-31',
  },
  {
    nom: 'IMT Atlantique',
    pays: 'France', ville: 'Nantes / Brest / Rennes', code_pays: 'fr',
    type: 'grande_ecole',
    domaines: ['Ingénierie', 'Numérique', 'Énergie', 'Sciences de la mer'],
    niveaux: ['Master', 'Doctorat'],
    langue: 'Français/Anglais', niveau_langue: 'B2',
    taux_admission: 22,
    frais_scolarite: '3 170 €/an (hors bourse)',
    frais_inscription: '92 €/an',
    moyenne_requise: 14.00,
    classement_mondial: null, classement_national: null,
    description: 'Grande école d\'ingénieurs publique de référence en numérique, énergie et sciences de la mer. Diplôme reconnu bac+5 ingénieur.',
    points_forts: ['Diplôme ingénieur bac+5', 'Forte demande des entreprises', 'Nombreuses bourses disponibles', 'Campus sur 3 villes'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'CV', 'Lettres de recommandation (x2)', 'DELF B2'],
    plateforme: 'Directe + Campus France',
    cout_plateforme: '50 €',
    lien_candidature: 'https://www.imt-atlantique.fr/fr/admission/candidature-internationale',
    lien_officiel: 'https://www.imt-atlantique.fr',
    date_ouverture: '2024-11-01', date_cloture: '2025-03-15',
  },

  // ══════════════════════════════════════════════════════════════
  // CANADA — 8 universités
  // ══════════════════════════════════════════════════════════════
  {
    nom: 'Université de Montréal',
    pays: 'Canada', ville: 'Montréal', code_pays: 'ca',
    type: 'publique',
    domaines: ['Médecine', 'Droit', 'Sciences', 'Informatique', 'Sciences humaines'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 52,
    frais_scolarite: '7 000 - 12 000 CAD/an (étudiants étrangers)',
    frais_inscription: '110 CAD (frais de dossier)',
    moyenne_requise: 13.00,
    classement_mondial: 141, classement_national: 3,
    description: 'Université francophone de référence en Amérique du Nord. Forte communauté africaine. Montréal est la capitale mondiale des étudiants selon plusieurs classements.',
    points_forts: ['Francophone', 'Forte communauté africaine', 'Montréal = ville étudiante #1', 'Bonne qualité de vie'],
    documents_requis: ['Relevés de notes officiels', 'Diplôme apostillé', 'Lettre de motivation', 'CV', 'Passeport', 'DELF/TCF B2 minimum', 'Preuve de fonds (15 000 CAD/an)'],
    plateforme: 'Directe (site UdeM)',
    cout_plateforme: '110 CAD (≈ 75 €)',
    lien_candidature: 'https://admission.umontreal.ca/candidature/',
    lien_officiel: 'https://www.umontreal.ca',
    date_ouverture: '2024-10-01', date_cloture: '2025-02-01',
  },
  {
    nom: 'Université McGill',
    pays: 'Canada', ville: 'Montréal', code_pays: 'ca',
    type: 'publique',
    domaines: ['Médecine', 'Droit', 'Ingénierie', 'Sciences', 'Management'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Anglais', niveau_langue: 'C1',
    taux_admission: 38,
    frais_scolarite: '20 000 - 30 000 CAD/an',
    frais_inscription: '120 CAD',
    moyenne_requise: 15.00,
    classement_mondial: 30, classement_national: 1,
    description: 'Meilleure université canadienne selon QS. Cours en anglais. Reconnue mondialement. Formation très compétitive avec d\'excellents débouchés.',
    points_forts: ['#30 mondial QS', 'Reconnaissance internationale', 'Réseau alumni global', 'Forte en recherche'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'Lettre de motivation', 'CV', 'IELTS 6.5 ou TOEFL 90', 'Lettres de recommandation (x2)', 'Passeport'],
    plateforme: 'Directe (McGill Apply)',
    cout_plateforme: '120 CAD (≈ 82 €)',
    lien_candidature: 'https://www.mcgill.ca/apply/',
    lien_officiel: 'https://www.mcgill.ca',
    date_ouverture: '2024-09-01', date_cloture: '2025-01-15',
  },
  {
    nom: 'Université Laval',
    pays: 'Canada', ville: 'Québec', code_pays: 'ca',
    type: 'publique',
    domaines: ['Droit', 'Sciences forestières', 'Génie', 'Sciences de la santé', 'Agriculture'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 55,
    frais_scolarite: '8 000 - 13 000 CAD/an',
    frais_inscription: '100 CAD',
    moyenne_requise: 12.50,
    classement_mondial: 401, classement_national: 5,
    description: 'Université francophone historique du Québec. Ville de Québec plus abordable que Montréal. Très bon accueil des étudiants africains.',
    points_forts: ['Francophone', 'Moins chère que Montréal', 'Très bon accueil international', 'Droit civil québécois unique'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'Lettre de motivation', 'CV', 'DELF/TCF B2', 'Passeport', 'Preuve de fonds'],
    plateforme: 'Directe (site Laval)',
    cout_plateforme: '100 CAD (≈ 68 €)',
    lien_candidature: 'https://www.ulaval.ca/admission/candidature',
    lien_officiel: 'https://www.ulaval.ca',
    date_ouverture: '2024-10-01', date_cloture: '2025-02-15',
  },
  {
    nom: 'Université d\'Ottawa',
    pays: 'Canada', ville: 'Ottawa', code_pays: 'ca',
    type: 'publique',
    domaines: ['Droit', 'Sciences sociales', 'Génie', 'Médecine', 'Gestion'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français/Anglais', niveau_langue: 'B2',
    taux_admission: 48,
    frais_scolarite: '22 000 - 28 000 CAD/an',
    frais_inscription: '100 CAD',
    moyenne_requise: 13.00,
    classement_mondial: 203, classement_national: 4,
    description: 'Seule université bilingue de sa taille au monde. Capitale fédérale du Canada. Accès aux institutions gouvernementales et aux ONG internationales.',
    points_forts: ['Bilingue français/anglais', 'Réseau politique unique', 'Stage gouvernement fédéral', 'Double diplôme possible'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'CV', 'DELF B2 ou IELTS 6.5', 'Passeport'],
    plateforme: 'Directe (uOttawa)',
    cout_plateforme: '100 CAD (≈ 68 €)',
    lien_candidature: 'https://admission.uottawa.ca/en/',
    lien_officiel: 'https://www.uottawa.ca',
    date_ouverture: '2024-10-01', date_cloture: '2025-03-01',
  },
  {
    nom: 'HEC Montréal',
    pays: 'Canada', ville: 'Montréal', code_pays: 'ca',
    type: 'grande_ecole',
    domaines: ['Management', 'Finance', 'Comptabilité', 'Marketing', 'Entrepreneuriat'],
    niveaux: ['Master'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 45,
    frais_scolarite: '15 000 - 20 000 CAD/an',
    frais_inscription: '130 CAD',
    moyenne_requise: 13.50,
    classement_mondial: null, classement_national: null,
    description: 'La meilleure école de commerce francophone d\'Amérique du Nord. MBA et Master très reconnus par les employeurs. Triple accréditation AACSB, EQUIS, AMBA.',
    points_forts: ['Triple accréditation (seule école fr. en Amérique)', 'MBA reconnu mondialement', 'Réseau affaires Québec', 'Placement emploi 95%'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'CV', 'Lettre de motivation', 'Lettres de recommandation (x2)', 'GMAT ou GRE (MSc)', 'DELF B2'],
    plateforme: 'Directe (HEC)',
    cout_plateforme: '130 CAD (≈ 89 €)',
    lien_candidature: 'https://www.hec.ca/admission/',
    lien_officiel: 'https://www.hec.ca',
    date_ouverture: '2024-10-01', date_cloture: '2025-02-01',
  },
  {
    nom: 'Université de Sherbrooke',
    pays: 'Canada', ville: 'Sherbrooke', code_pays: 'ca',
    type: 'publique',
    domaines: ['Génie', 'Sciences', 'Droit', 'Médecine', 'Administration'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 58,
    frais_scolarite: '6 500 - 10 000 CAD/an',
    frais_inscription: '100 CAD',
    moyenne_requise: 12.00,
    classement_mondial: 601, classement_national: 8,
    description: 'Pionnière de la formation coopérative (alternance) au Canada. Ville abordable. Formation pratique avec stages intégrés dans le cursus.',
    points_forts: ['Formation coopérative (stage intégré)', 'Moins chère que Montréal', 'Communauté africaine active', 'Bon taux d\'admission'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'CV', 'DELF B2'],
    plateforme: 'Directe (UdeS)',
    cout_plateforme: '100 CAD (≈ 68 €)',
    lien_candidature: 'https://www.usherbrooke.ca/admission/',
    lien_officiel: 'https://www.usherbrooke.ca',
    date_ouverture: '2024-11-01', date_cloture: '2025-03-01',
  },
  {
    nom: 'UQAM - Université du Québec à Montréal',
    pays: 'Canada', ville: 'Montréal', code_pays: 'ca',
    type: 'publique',
    domaines: ['Arts', 'Sciences humaines', 'Droit', 'Sciences', 'Communication'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 62,
    frais_scolarite: '6 000 - 9 000 CAD/an',
    frais_inscription: '80 CAD',
    moyenne_requise: 11.50,
    classement_mondial: 801, classement_national: 10,
    description: 'Université progressiste au cœur de Montréal. Frais parmi les plus bas du Québec pour les étudiants étrangers. Forte en sciences humaines et arts.',
    points_forts: ['Frais les plus bas du Québec', 'Au cœur de Montréal', 'Bonne accessibilité', 'Arts et comm reconnus'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'DELF B2'],
    plateforme: 'Directe (UQAM)',
    cout_plateforme: '80 CAD (≈ 55 €)',
    lien_candidature: 'https://admission.uqam.ca/',
    lien_officiel: 'https://www.uqam.ca',
    date_ouverture: '2024-11-01', date_cloture: '2025-03-15',
  },
  {
    nom: 'Polytechnique Montréal',
    pays: 'Canada', ville: 'Montréal', code_pays: 'ca',
    type: 'grande_ecole',
    domaines: ['Génie civil', 'Génie informatique', 'Génie électrique', 'Génie mécanique'],
    niveaux: ['Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 35,
    frais_scolarite: '10 000 - 16 000 CAD/an',
    frais_inscription: '120 CAD',
    moyenne_requise: 14.00,
    classement_mondial: null, classement_national: null,
    description: 'La plus grande école d\'ingénieurs francophone en Amérique. Étroitement liée à l\'UdeM. Très bon financement pour les doctorants.',
    points_forts: ['Meilleure école ingé francophone Amérique', 'Financement doctorat élevé', 'Partenariats Bombardier, CAE, Ubisoft', 'Diplôme reconnu mondialement'],
    documents_requis: ['Relevés de notes', 'Diplôme ingénieur', 'CV', 'Lettre de motivation', 'DELF B2', 'Lettres de recommandation (x2)'],
    plateforme: 'Directe (Polytechnique)',
    cout_plateforme: '120 CAD (≈ 82 €)',
    lien_candidature: 'https://www.polymtl.ca/admission/',
    lien_officiel: 'https://www.polymtl.ca',
    date_ouverture: '2024-10-01', date_cloture: '2025-02-15',
  },

  // ══════════════════════════════════════════════════════════════
  // BELGIQUE — 4 universités
  // ══════════════════════════════════════════════════════════════
  {
    nom: 'UCLouvain',
    pays: 'Belgique', ville: 'Louvain-la-Neuve', code_pays: 'be',
    type: 'publique',
    domaines: ['Médecine', 'Sciences', 'Droit', 'Ingénierie', 'Théologie'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 55,
    frais_scolarite: '835 - 4 175 €/an selon revenus',
    frais_inscription: '835 €/an (minerval)',
    moyenne_requise: 12.50,
    classement_mondial: 201, classement_national: 1,
    description: 'Meilleure université francophone de Belgique. Ville universitaire construite pour les étudiants. Frais modulés selon les revenus. Campus vert et moderne.',
    points_forts: ['#1 Belgique francophone', 'Ville étudiante unique', 'Frais modérés', 'Campus vert et sûr'],
    documents_requis: ['Relevés de notes', 'Diplôme légalisé', 'Lettre de motivation', 'CV', 'Passeport', 'DELF B2'],
    plateforme: 'Directe (UCLouvain)',
    cout_plateforme: '0 € (pas de frais de dossier)',
    lien_candidature: 'https://uclouvain.be/fr/etudier/inscriptions',
    lien_officiel: 'https://uclouvain.be',
    date_ouverture: '2024-11-01', date_cloture: '2025-04-30',
  },
  {
    nom: 'ULB - Université Libre de Bruxelles',
    pays: 'Belgique', ville: 'Bruxelles', code_pays: 'be',
    type: 'publique',
    domaines: ['Sciences politiques', 'Droit', 'Sciences', 'Architecture', 'Médecine'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 52,
    frais_scolarite: '835 - 4 175 €/an',
    frais_inscription: '835 €/an',
    moyenne_requise: 13.00,
    classement_mondial: 224, classement_national: 2,
    description: 'Au cœur de Bruxelles, capitale européenne. 6 Prix Nobel. Forte en droit européen et sciences politiques. Accès aux institutions EU (Parlement, Commission).',
    points_forts: ['Bruxelles = capitale EU', 'Accès institutions européennes', '6 Prix Nobel', 'Stage UE possible'],
    documents_requis: ['Relevés de notes', 'Diplôme légalisé/apostillé', 'Lettre de motivation', 'CV', 'DELF B2'],
    plateforme: 'Directe (ULB)',
    cout_plateforme: '0 €',
    lien_candidature: 'https://www.ulb.be/fr/comment-sinscrire',
    lien_officiel: 'https://www.ulb.be',
    date_ouverture: '2024-11-01', date_cloture: '2025-04-30',
  },
  {
    nom: 'Université de Liège',
    pays: 'Belgique', ville: 'Liège', code_pays: 'be',
    type: 'publique',
    domaines: ['Ingénierie', 'Sciences', 'Médecine vétérinaire', 'Droit', 'HEC'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 60,
    frais_scolarite: '835 - 4 000 €/an',
    frais_inscription: '835 €/an',
    moyenne_requise: 12.00,
    classement_mondial: 401, classement_national: 3,
    description: 'Forte en ingénierie et médecine vétérinaire. Liège est la 3ème ville de Belgique, moins chère que Bruxelles. Excellent rapport qualité/coût.',
    points_forts: ['Ingénierie reconnue', 'Moins chère que Bruxelles', 'Proximité Luxembourg/Allemagne', 'Communauté africaine active'],
    documents_requis: ['Relevés de notes', 'Diplôme légalisé', 'Lettre de motivation', 'CV', 'DELF B2'],
    plateforme: 'Directe (ULiège)',
    cout_plateforme: '0 €',
    lien_candidature: 'https://www.uliege.be/admission',
    lien_officiel: 'https://www.uliege.be',
    date_ouverture: '2024-11-01', date_cloture: '2025-04-30',
  },
  {
    nom: 'Université de Namur (UNamur)',
    pays: 'Belgique', ville: 'Namur', code_pays: 'be',
    type: 'publique',
    domaines: ['Informatique', 'Droit', 'Sciences', 'Économie', 'Philosophie'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Français', niveau_langue: 'B2',
    taux_admission: 68,
    frais_scolarite: '835 - 3 500 €/an',
    frais_inscription: '835 €/an',
    moyenne_requise: 11.50,
    classement_mondial: 801, classement_national: 4,
    description: 'Petite université à taille humaine. Très bon suivi individuel. Namur est une ville calme et abordable. Forte en informatique et sécurité des systèmes.',
    points_forts: ['Petite taille = suivi personnalisé', 'Informatique reconnu', 'Ville abordable', 'Bon taux d\'admission'],
    documents_requis: ['Relevés de notes', 'Diplôme', 'Lettre de motivation', 'DELF B2'],
    plateforme: 'Directe (UNamur)',
    cout_plateforme: '0 €',
    lien_candidature: 'https://www.unamur.be/etudes/admissions',
    lien_officiel: 'https://www.unamur.be',
    date_ouverture: '2024-11-01', date_cloture: '2025-06-30',
  },

  // ══════════════════════════════════════════════════════════════
  // ALLEMAGNE — 4 universités
  // ══════════════════════════════════════════════════════════════
  {
    nom: 'Technische Universität München (TUM)',
    pays: 'Allemagne', ville: 'Munich', code_pays: 'de',
    type: 'publique',
    domaines: ['Ingénierie', 'Sciences', 'Informatique', 'Architecture', 'Médecine'],
    niveaux: ['Master', 'Doctorat'],
    langue: 'Anglais/Allemand', niveau_langue: 'B2',
    taux_admission: 20,
    frais_scolarite: '0 € (frais publics) + 258 € semestre (frais admin)',
    frais_inscription: '258 €/semestre',
    moyenne_requise: 15.00,
    classement_mondial: 37, classement_national: 1,
    description: 'Meilleure université technique d\'Allemagne. Nombreux masters en anglais. 0 € de frais de scolarité. Forte demande des entreprises tech mondiales.',
    points_forts: ['Frais quasi nuls', '#37 mondial', 'Nombreux masters en anglais', 'BMW, Siemens, MAN recrutent directement'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'CV', 'Lettre de motivation', 'IELTS 6.5 ou TestDaF', 'APS Certificate (Étudiants africains)', 'Passeport'],
    plateforme: 'Uni-Assist + directe TUM',
    cout_plateforme: '75 € (Uni-Assist) + 30 €/université',
    lien_candidature: 'https://www.tum.de/en/studies/application/',
    lien_officiel: 'https://www.tum.de',
    date_ouverture: '2025-01-01', date_cloture: '2025-05-31',
  },
  {
    nom: 'Ludwig Maximilian Universität München (LMU)',
    pays: 'Allemagne', ville: 'Munich', code_pays: 'de',
    type: 'publique',
    domaines: ['Médecine', 'Droit', 'Sciences humaines', 'Économie', 'Sciences'],
    niveaux: ['Master', 'Doctorat'],
    langue: 'Allemand/Anglais', niveau_langue: 'B2',
    taux_admission: 25,
    frais_scolarite: '0 € + 258 €/semestre admin',
    frais_inscription: '258 €/semestre',
    moyenne_requise: 14.50,
    classement_mondial: 54, classement_national: 2,
    description: 'L\'une des universités les plus anciennes d\'Allemagne. Excellente en médecine et sciences humaines. 44 Prix Nobel.',
    points_forts: ['44 Prix Nobel', 'Frais nuls', 'Médecine réputée mondialement', 'Munich = capitale économique'],
    documents_requis: ['Relevés de notes apostillés', 'Diplôme', 'CV', 'Lettre de motivation', 'TestDaF ou IELTS', 'APS Certificate', 'Passeport'],
    plateforme: 'Uni-Assist',
    cout_plateforme: '75 € + 30 €/université (Uni-Assist)',
    lien_candidature: 'https://www.lmu.de/en/studies/application-and-enrollment/',
    lien_officiel: 'https://www.lmu.de',
    date_ouverture: '2025-01-01', date_cloture: '2025-05-15',
  },
  {
    nom: 'RWTH Aachen',
    pays: 'Allemagne', ville: 'Aachen', code_pays: 'de',
    type: 'publique',
    domaines: ['Génie mécanique', 'Génie électrique', 'Informatique', 'Architecture'],
    niveaux: ['Master', 'Doctorat'],
    langue: 'Allemand/Anglais', niveau_langue: 'B2',
    taux_admission: 30,
    frais_scolarite: '0 € + 284 €/semestre',
    frais_inscription: '284 €/semestre',
    moyenne_requise: 14.00,
    classement_mondial: 106, classement_national: 3,
    description: 'La Harvard de l\'ingénierie européenne. Étroitement liée à Ford, Thyssen, BASF. Aachen est frontalière avec Belgique et Pays-Bas.',
    points_forts: ['Référence mondiale ingénierie', 'Partenariats Ford/BASF/Thyssen', 'Frontalier Belgique/NL', 'Frais quasi nuls'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'CV', 'Lettre de motivation', 'TestDaF ou IELTS 6.5', 'APS Certificate'],
    plateforme: 'Uni-Assist + directe',
    cout_plateforme: '75 € + 30 € (Uni-Assist)',
    lien_candidature: 'https://www.rwth-aachen.de/cms/root/Studium/Vor-dem-Studium/Bewerbung/~dmd/Internationale-Bewerber/',
    lien_officiel: 'https://www.rwth-aachen.de',
    date_ouverture: '2025-01-15', date_cloture: '2025-05-15',
  },
  {
    nom: 'Freie Universität Berlin',
    pays: 'Allemagne', ville: 'Berlin', code_pays: 'de',
    type: 'publique',
    domaines: ['Sciences politiques', 'Sciences humaines', 'Sciences', 'Droit', 'Médecine'],
    niveaux: ['Master', 'Doctorat'],
    langue: 'Allemand/Anglais', niveau_langue: 'B2',
    taux_admission: 35,
    frais_scolarite: '0 € + 313 €/semestre',
    frais_inscription: '313 €/semestre',
    moyenne_requise: 13.50,
    classement_mondial: 98, classement_national: 4,
    description: 'Fondée par des étudiants en 1948. Berlin = ville cosmopolite et créative, coût de vie parmi les plus bas d\'Europe occidentale.',
    points_forts: ['Berlin = hub startup européen', 'Top 100 mondial', 'Coût de vie modéré', 'Sciences humaines exceptionnelles'],
    documents_requis: ['Relevés de notes', 'Diplôme apostillé', 'Lettre de motivation', 'CV', 'TestDaF B2 ou IELTS 6.5', 'APS Certificate'],
    plateforme: 'Uni-Assist',
    cout_plateforme: '75 € + 30 €/université',
    lien_candidature: 'https://www.fu-berlin.de/studium/bewerbung/',
    lien_officiel: 'https://www.fu-berlin.de',
    date_ouverture: '2025-01-01', date_cloture: '2025-05-31',
  },

  // ══════════════════════════════════════════════════════════════
  // ROYAUME-UNI — 4 universités
  // ══════════════════════════════════════════════════════════════
  {
    nom: 'University of Edinburgh',
    pays: 'Royaume-Uni', ville: 'Édimbourg', code_pays: 'gb',
    type: 'publique',
    domaines: ['Médecine', 'Sciences', 'Droit', 'Informatique', 'Arts'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Anglais', niveau_langue: 'C1',
    taux_admission: 30,
    frais_scolarite: '17 800 - 26 500 £/an',
    frais_inscription: '0 £',
    moyenne_requise: 14.50,
    classement_mondial: 22, classement_national: 5,
    description: 'Top 25 mondial. Ville magnifique, frais de vie moins élevés que Londres. Forte en médecine, informatique et arts. Via UCAS.',
    points_forts: ['Top 25 mondial', 'Moins cher que Londres', 'Médecine et info excellents', 'Cadre historique'],
    documents_requis: ['Relevés de notes (3 dernières années)', 'CV', 'Personal statement', 'Référence académique (x1)', 'IELTS 6.5-7.0'],
    plateforme: 'UCAS',
    cout_plateforme: '27.50 £ (≈ 32 €) pour 5 vœux UCAS',
    lien_candidature: 'https://www.ucas.com',
    lien_officiel: 'https://www.ed.ac.uk',
    date_ouverture: '2024-09-01', date_cloture: '2025-01-15',
  },
  {
    nom: 'University of Manchester',
    pays: 'Royaume-Uni', ville: 'Manchester', code_pays: 'gb',
    type: 'publique',
    domaines: ['Sciences', 'Ingénierie', 'Médecine', 'Économie', 'Architecture'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Anglais', niveau_langue: 'C1',
    taux_admission: 32,
    frais_scolarite: '16 000 - 28 000 £/an',
    frais_inscription: '0 £',
    moyenne_requise: 14.00,
    classement_mondial: 32, classement_national: 6,
    description: '25 Prix Nobel. Forte en physique, économie et science des matériaux. Manchester = 2ème ville étudiante du Royaume-Uni. Plus abordable que Londres.',
    points_forts: ['25 Prix Nobel', 'Moins chère que Londres', 'Forte communauté internationale', 'Graphène inventé ici'],
    documents_requis: ['Relevés de notes', 'CV', 'Personal statement', 'Références (x2)', 'IELTS 6.5'],
    plateforme: 'UCAS',
    cout_plateforme: '27.50 £',
    lien_candidature: 'https://www.ucas.com',
    lien_officiel: 'https://www.manchester.ac.uk',
    date_ouverture: '2024-09-01', date_cloture: '2025-01-15',
  },
  {
    nom: 'King\'s College London',
    pays: 'Royaume-Uni', ville: 'Londres', code_pays: 'gb',
    type: 'publique',
    domaines: ['Droit', 'Médecine', 'Sciences', 'Arts', 'Relations internationales'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Anglais', niveau_langue: 'C1',
    taux_admission: 25,
    frais_scolarite: '19 500 - 33 000 £/an',
    frais_inscription: '0 £',
    moyenne_requise: 15.00,
    classement_mondial: 40, classement_national: 7,
    description: 'Russell Group. Au cœur de Londres sur la Tamise. Droit international et médecine parmi les meilleurs au monde. Réseau alumni dans les organisations internationales.',
    points_forts: ['Au cœur de Londres', 'Droit international #1', 'Réseau ONU/OMS/ONG', 'Russell Group'],
    documents_requis: ['Relevés de notes', 'Personal statement', 'Références (x2)', 'IELTS 7.0'],
    plateforme: 'UCAS',
    cout_plateforme: '27.50 £',
    lien_candidature: 'https://www.ucas.com',
    lien_officiel: 'https://www.kcl.ac.uk',
    date_ouverture: '2024-09-01', date_cloture: '2025-01-15',
  },
  {
    nom: 'University of Birmingham',
    pays: 'Royaume-Uni', ville: 'Birmingham', code_pays: 'gb',
    type: 'publique',
    domaines: ['Ingénierie', 'Sciences', 'Droit', 'Économie', 'Médecine'],
    niveaux: ['Licence', 'Master', 'Doctorat'],
    langue: 'Anglais', niveau_langue: 'B2',
    taux_admission: 42,
    frais_scolarite: '14 200 - 22 500 £/an',
    frais_inscription: '0 £',
    moyenne_requise: 13.50,
    classement_mondial: 84, classement_national: 12,
    description: 'Russell Group. Birmingham est plus abordable que Londres tout en étant bien connectée. Forte en ingénierie et sciences. Bon taux d\'admission pour les internationaux.',
    points_forts: ['Plus accessible que Londres', 'Russell Group', 'Ingénierie reconnue', 'Bonne communauté africaine'],
    documents_requis: ['Relevés de notes', 'Personal statement', 'Référence (x1)', 'IELTS 6.0-6.5'],
    plateforme: 'UCAS',
    cout_plateforme: '27.50 £',
    lien_candidature: 'https://www.ucas.com',
    lien_officiel: 'https://www.birmingham.ac.uk',
    date_ouverture: '2024-09-01', date_cloture: '2025-01-15',
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    let inserted = 0, skipped = 0;

    for (const u of universities) {
      const exists = await client.query(
        'SELECT id FROM universities WHERE nom = $1 AND pays = $2',
        [u.nom, u.pays]
      );
      if (exists.rows.length > 0) { skipped++; continue; }

      await client.query(`
        INSERT INTO universities (
          nom, pays, ville, code_pays, type,
          domaines, niveaux, langue, niveau_langue,
          taux_admission, frais_scolarite, frais_inscription, moyenne_requise,
          classement_mondial, classement_national,
          description, points_forts, documents_requis,
          plateforme, cout_plateforme, lien_candidature, lien_officiel,
          date_ouverture, date_cloture
        ) VALUES (
          $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,
          $16,$17,$18,$19,$20,$21,$22,$23,$24
        )
      `, [
        u.nom, u.pays, u.ville, u.code_pays, u.type,
        u.domaines, u.niveaux, u.langue, u.niveau_langue,
        u.taux_admission, u.frais_scolarite, u.frais_inscription, u.moyenne_requise,
        u.classement_mondial || null, u.classement_national || null,
        u.description, u.points_forts, u.documents_requis,
        u.plateforme, u.cout_plateforme, u.lien_candidature, u.lien_officiel,
        u.date_ouverture || null, u.date_cloture || null,
      ]);
      inserted++;
    }

    console.log(`✅ Universités : ${inserted} insérées, ${skipped} déjà présentes.`);
  } catch (err) {
    console.error('❌ Erreur seed universités:', err.message);
    throw err;
  } finally {
    client.release();
  }
}

seed().then(() => process.exit(0)).catch(() => process.exit(1));
