const pool = require('../config/database');

// Calcule date_debut = deadline - 3 mois
function dateDebut(deadline) {
  const d = new Date(deadline);
  d.setMonth(d.getMonth() - 3);
  return d.toISOString().split('T')[0];
}

const scholarships = [

  // ─── FRANCE ────────────────────────────────────────────────────────────────

  {
    nom: 'Bourse Eiffel Excellence',
    organisme: 'Campus France / Ministère des Affaires Étrangères',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '1 181 €/mois + avantages',
    deadline: '2027-01-09',
    date_debut: '2026-10-01',
    duree: '1 à 3 ans',
    type_financement: 'Complète',
    description: 'Bourse d\'excellence destinée aux meilleurs étudiants étrangers souhaitant poursuivre des études de Master en France. Inclut allocation mensuelle, transport international, couverture médicale et activités culturelles.',
    lien: 'https://www.campusfrance.org/fr/eiffel',
    avantages: ['Allocation mensuelle (1 181 €)', 'Billet d\'avion aller-retour', 'Assurance maladie', 'Aide au logement', 'Activités culturelles', 'Accueil à l\'arrivée'],
    documents_requis: ['CV en français', 'Lettre de motivation (2 pages max)', 'Relevés de notes des 3 dernières années', 'Diplôme le plus récent (traduit)', 'Deux lettres de recommandation', 'Certification de langue française (B2 min)', 'Passeport en cours de validité', 'Lettre d\'admission provisoire d\'un établissement français'],
    nationalites_eligibles: ['Tous pays d\'Afrique subsaharienne', 'Maghreb', 'Asie', 'Amériques'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 30,
    nb_places: 400,
    criteres: [
      { titre: 'Excellence académique', desc: 'Moyenne ≥ 14/20 sur les 3 dernières années' },
      { titre: 'Projet professionnel', desc: 'Projet clair en lien avec le développement du pays d\'origine' },
      { titre: 'Candidature institutionnelle', desc: 'Le dossier doit être déposé via l\'université française d\'accueil, pas directement' },
    ],
  },

  {
    nom: 'Bourse du Gouvernement Français (BGF)',
    organisme: 'Ambassade de France / Institut Français',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '700 – 1 000 €/mois',
    deadline: '2027-03-31',
    date_debut: '2026-12-01',
    duree: '1 à 2 ans',
    type_financement: 'Partielle',
    description: 'Bourse accordée par les ambassades de France aux étudiants de pays partenaires. Les montants et conditions varient selon le pays d\'origine et l\'ambassade.',
    lien: 'https://www.campusfrance.org/fr/bourses-du-gouvernement-francais-bgf',
    avantages: ['Allocation mensuelle (700-1 000 €)', 'Assurance maladie', 'Accompagnement administratif'],
    documents_requis: ['Dossier Campus France complet', 'CV', 'Lettre de motivation', 'Relevés de notes officiels', 'Diplôme avec traduction assermentée', 'Deux lettres de recommandation', 'Passeport'],
    nationalites_eligibles: ['Pays partenaires de la France en Afrique subsaharienne'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B1',
    age_max: 35,
    nb_places: null,
    criteres: [
      { titre: 'Dépôt via Campus France', desc: 'La candidature se fait obligatoirement via la plateforme Campus France de votre pays' },
      { titre: 'Admission préalable', desc: 'Vous devez avoir une admission dans un établissement français avant de candidater' },
    ],
  },

  {
    nom: 'Bourse AUF – Agence Universitaire de la Francophonie',
    organisme: 'AUF',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Tous domaines (priorité sciences et développement)',
    montant: '850 €/mois',
    deadline: '2027-04-15',
    date_debut: '2027-01-15',
    duree: '1 an renouvelable',
    type_financement: 'Partielle',
    description: 'Mobilité internationale de l\'AUF dans les établissements membres du réseau francophone. Cible les étudiants francophones du Sud voulant poursuivre un master dans un pays du Nord.',
    lien: 'https://www.auf.org/bourses/',
    avantages: ['Allocation mensuelle (850 €)', 'Couverture des frais de scolarité (partielle)', 'Accès aux ressources numériques AUF'],
    documents_requis: ['Dossier de candidature AUF en ligne', 'CV', 'Lettre de motivation', 'Relevés de notes officiels', 'Lettre de l\'établissement d\'accueil membre AUF', 'Deux lettres de recommandation académiques'],
    nationalites_eligibles: ['Pays francophones d\'Afrique subsaharienne', 'Maghreb', 'Haïti', 'Vietnam', 'Cambodge'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 40,
    nb_places: null,
    criteres: [
      { titre: 'Membre AUF', desc: 'Votre établissement d\'origine ET l\'établissement d\'accueil doivent être membres de l\'AUF' },
      { titre: 'Projet de recherche', desc: 'Définir clairement l\'apport de la formation pour votre pays d\'origine' },
    ],
  },

  {
    nom: 'Master Erasmus Mundus',
    organisme: 'Union Européenne – EACEA',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Tous domaines (programmes variés)',
    montant: '1 000 €/mois + frais de scolarité complets',
    deadline: '2027-01-15',
    date_debut: '2026-10-15',
    duree: '1 à 2 ans',
    type_financement: 'Complète',
    description: 'Programmes de master conjoint entre plusieurs universités européennes. Bourse complète incluant scolarité, allocation mensuelle, transport et assurance. L\'étudiant passe au minimum 1 semestre dans 2 pays différents.',
    lien: 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters',
    avantages: ['Frais de scolarité couverts à 100%', 'Allocation mensuelle (1 000 €)', 'Billet d\'avion international', 'Assurance maladie et accident', 'Visa et frais d\'installation'],
    documents_requis: ['CV (format Europass recommandé)', 'Lettre de motivation en anglais ou français', 'Diplôme de Licence (traduit et apostillé)', 'Relevés de notes officiels', 'Deux lettres de recommandation', 'Certification de langue (IELTS/TOEFL ou DELF/DALF)', 'Passeport', 'Déclaration d\'intention de retour dans le pays d\'origine'],
    nationalites_eligibles: ['Tous pays hors Union Européenne'],
    langue_requise: 'Anglais ou Français selon le programme',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: 25,
    criteres: [
      { titre: 'Diplôme de Licence validé', desc: 'Vous devez avoir obtenu votre Licence avant le début du programme' },
      { titre: 'Candidature à un programme spécifique', desc: 'Chaque programme Erasmus Mundus a son propre processus de sélection' },
    ],
  },

  {
    nom: 'Bourse Fondation Total Énergies',
    organisme: 'Fondation Total Énergies',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Énergie, Ingénierie, Sciences, Géosciences',
    montant: '1 000 €/mois',
    deadline: '2027-03-01',
    date_debut: '2026-12-01',
    duree: '1 à 2 ans',
    type_financement: 'Partielle',
    description: 'Programme de bourses pour étudiants africains d\'excellence souhaitant étudier dans les grandes écoles françaises dans les domaines de l\'énergie et des sciences.',
    lien: 'https://fondation.totalenergies.com/fr/programmes/bourses-afrique-subsaharienne',
    avantages: ['Allocation mensuelle (1 000 €)', 'Accès au réseau Total Énergies', 'Mentorat professionnel'],
    documents_requis: ['CV', 'Lettre de motivation orientée énergie', 'Relevés de notes officiels', 'Diplôme avec traduction', 'Deux lettres de recommandation', 'Preuve d\'admission dans une grande école française', 'Certification de langue'],
    nationalites_eligibles: ['Afrique subsaharienne francophone', 'Maghreb'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 30,
    nb_places: 50,
    criteres: [
      { titre: 'Domaine énergie/ingénierie', desc: 'Priorité aux domaines liés à l\'énergie, l\'environnement, les géosciences et l\'ingénierie' },
      { titre: 'Admission préalable', desc: 'Lettre d\'admission dans une grande école française obligatoire' },
    ],
  },

  {
    nom: 'Bourse Sciences Po Paris – Émile Boutmy',
    organisme: 'Sciences Po Paris',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Sciences Politiques, Droit, Économie, Relations Internationales',
    montant: 'Jusqu\'à 15 000 €/an',
    deadline: '2027-01-05',
    date_debut: '2026-10-01',
    duree: '1 à 2 ans',
    type_financement: 'Partielle',
    description: 'Bourse méritocratique de Sciences Po destinée aux meilleurs étudiants internationaux hors UE. Critères académiques très stricts. Sélection sur dossier.',
    lien: 'https://www.sciencespo.fr/fr/international/bourses',
    avantages: ['Aide financière annuelle (jusqu\'à 15 000 €)', 'Accès au réseau Sciences Po', 'Logement en résidence universitaire prioritaire'],
    documents_requis: ['Dossier de candidature Sciences Po', 'CV', 'Deux essais de motivation', 'Relevés de notes', 'Diplôme', 'Deux lettres de recommandation', 'Certification de langue (français et anglais)'],
    nationalites_eligibles: ['Tous pays hors Union Européenne'],
    langue_requise: 'Français et Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Excellence académique', desc: 'Exige un très haut niveau académique, dans le top 10% de votre promotion' },
      { titre: 'Maîtrise du français ET de l\'anglais', desc: 'Les cours à Sciences Po sont dispensés en français et en anglais' },
    ],
  },

  {
    nom: 'Bourses ENS Paris – International',
    organisme: 'École Normale Supérieure de Paris',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Sciences, Mathématiques, Lettres, Philosophie',
    montant: '1 000 €/mois',
    deadline: '2027-02-28',
    date_debut: '2026-11-01',
    duree: '1 an renouvelable',
    type_financement: 'Complète',
    description: 'Sélection internationale très sélective de l\'ENS pour des étudiants brillants du monde entier. L\'ENS est l\'une des meilleures grandes écoles françaises.',
    lien: 'https://www.ens.psl.eu/en/international/admission-international-students',
    avantages: ['Allocation mensuelle (1 000 €)', 'Logement en résidence ENS', 'Accès aux laboratoires de recherche', 'Couverture sociale'],
    documents_requis: ['Dossier en ligne ENS', 'CV académique détaillé', 'Lettre de motivation scientifique', 'Relevés de notes complets', 'Deux lettres de recommandation de professeurs', 'Publications ou travaux de recherche (si disponibles)', 'Certification de langue française (C1 souhaité)'],
    nationalites_eligibles: ['Tous pays hors France'],
    langue_requise: 'Français',
    niveau_langue_requis: 'C1',
    age_max: 26,
    nb_places: 30,
    criteres: [
      { titre: 'Niveau académique exceptionnel', desc: 'L\'ENS Paris accueille les meilleurs étudiants mondiaux. Dossier exceptionnel requis.' },
      { titre: 'Projet de recherche', desc: 'Un projet de recherche défini est nécessaire avec mention du laboratoire d\'accueil souhaité' },
    ],
  },

  {
    nom: 'Bourse CNOUS – Aide aux étudiants étrangers',
    organisme: 'CNOUS / CROUS',
    pays: 'France', code_pays: 'fr',
    niveau: 'Licence',
    domaine: 'Tous domaines',
    montant: '200 – 600 €/mois',
    deadline: '2027-05-31',
    date_debut: '2027-03-01',
    duree: '1 an renouvelable',
    type_financement: 'Partielle',
    description: 'Aides sociales aux étudiants étrangers en situation de précarité inscrits dans les universités françaises. Accessible après inscription.',
    lien: 'https://www.etudiant.gouv.fr/fr/bourses-et-aides',
    avantages: ['Allocation mensuelle variable', 'Accès au restaurant universitaire (tarif réduit)', 'Logement CROUS prioritaire'],
    documents_requis: ['Inscription universitaire', 'Justificatif de ressources', 'Passeport', 'Titre de séjour étudiant'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B1',
    age_max: 28,
    nb_places: null,
    criteres: [
      { titre: 'Critères sociaux', desc: 'Attribution basée sur les revenus de la famille. Simulation possible sur messervices.etudiant.gouv.fr' },
    ],
  },

  {
    nom: 'Prix Senghor de la Francophonie',
    organisme: 'Organisation Internationale de la Francophonie',
    pays: 'France', code_pays: 'fr',
    niveau: 'Doctorat',
    domaine: 'Lettres, Sciences Humaines, Arts, Francophonie',
    montant: '5 000 € (prix unique)',
    deadline: '2027-06-30',
    date_debut: '2027-02-01',
    duree: 'Prix unique (non bourse mensuelle)',
    type_financement: 'Partielle',
    description: 'Prix récompensant des travaux de recherche en français contribuant à la diversité culturelle et à la francophonie. Ce n\'est pas une bourse mensuelle mais un prix de reconnaissance.',
    lien: 'https://www.francophonie.org',
    avantages: ['Prix de 5 000 €', 'Reconnaissance internationale', 'Publication possible des travaux'],
    documents_requis: ['Thèse ou mémoire de recherche en français', 'CV', 'Lettre de présentation', 'Avis favorable d\'un directeur de recherche', 'Résumé du travail (5 pages max)'],
    nationalites_eligibles: ['Pays membres de l\'OIF'],
    langue_requise: 'Français',
    niveau_langue_requis: 'C1',
    age_max: 40,
    nb_places: 3,
    criteres: [
      { titre: 'Travaux en français', desc: 'La thèse ou le mémoire doit être rédigé en français' },
      { titre: 'Contribution à la francophonie', desc: 'Les travaux doivent contribuer à la diversité culturelle ou à la promotion du français' },
    ],
  },

  {
    nom: 'Bourse Fondation de France',
    organisme: 'Fondation de France',
    pays: 'France', code_pays: 'fr',
    niveau: 'Doctorat',
    domaine: 'Recherche scientifique, Médecine, Sciences sociales',
    montant: '1 200 €/mois',
    deadline: '2027-09-30',
    date_debut: '2027-06-01',
    duree: '1 à 3 ans',
    type_financement: 'Partielle',
    description: 'Financement de projets de recherche innovants par de jeunes chercheurs étrangers en France dans des domaines variés.',
    lien: 'https://www.fondationdefrance.org',
    avantages: ['Allocation mensuelle (1 200 €)', 'Financement des frais de recherche', 'Accès aux réseaux de recherche français'],
    documents_requis: ['Projet de recherche détaillé (10 pages)', 'CV académique', 'Lettre de l\'établissement d\'accueil', 'Deux lettres de recommandation de chercheurs', 'Publications existantes (si disponibles)'],
    nationalites_eligibles: ['Tous pays hors France'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 40,
    nb_places: null,
    criteres: [
      { titre: 'Projet de recherche innovant', desc: 'Le projet doit avoir un potentiel d\'impact concret et mesurable' },
      { titre: 'Partenariat avec un laboratoire français', desc: 'Un accord avec un laboratoire français accueillant est requis' },
    ],
  },

  {
    nom: 'Bourse HEC Paris – Excellence',
    organisme: 'HEC Paris',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'Commerce, Gestion, Finance, Entrepreneuriat',
    montant: 'Jusqu\'à 25 000 €',
    deadline: '2027-03-15',
    date_debut: '2026-12-01',
    duree: '1 à 2 ans',
    type_financement: 'Partielle',
    description: 'Bourse pour étudiants internationaux exceptionnels admis dans les programmes Grande École ou Masters d\'HEC Paris. Sélection sur dossier académique et test GMAT/GRE.',
    lien: 'https://www.hec.edu/fr/international',
    avantages: ['Aide financière (jusqu\'à 25 000 €)', 'Accès réseau HEC mondial', 'Mentorat par alumni'],
    documents_requis: ['Dossier HEC complet', 'GMAT ou GRE (score élevé requis)', 'CV en anglais', 'Essais de motivation', 'Deux lettres de recommandation professionnelles', 'Transcripts officiels', 'IELTS ou TOEFL (score ≥ 100 TOEFL)'],
    nationalites_eligibles: ['Tous pays hors France'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'GMAT/GRE requis', desc: 'Un score élevé au GMAT (700+) ou GRE est pratiquement indispensable' },
      { titre: 'Expérience professionnelle', desc: 'HEC valorise 2-5 ans d\'expérience professionnelle pour ses programmes MBA/Masters' },
    ],
  },

  {
    nom: 'Bourse INSEAD – Programme Afrique',
    organisme: 'INSEAD',
    pays: 'France', code_pays: 'fr',
    niveau: 'Master',
    domaine: 'MBA, Gestion, Leadership',
    montant: 'Variable (partiel)',
    deadline: '2027-04-01',
    date_debut: '2027-01-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'Bourses pour étudiants africains entrant dans le programme MBA de l\'INSEAD Fontainebleau. L\'INSEAD est classée top 5 mondiale en business.',
    lien: 'https://www.insead.edu/mba/financial-aid',
    avantages: ['Aide financière variable', 'Accès au réseau INSEAD mondial (60 000+ alumni)', 'Possibilité de stage en entreprise'],
    documents_requis: ['Dossier INSEAD complet', 'GMAT (score 700+ recommandé)', 'CV en anglais', '3 essais de motivation', 'Deux lettres de recommandation', 'TOEFL/IELTS'],
    nationalites_eligibles: ['Tous pays d\'Afrique'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'C1',
    age_max: 40,
    nb_places: null,
    criteres: [
      { titre: 'Expérience professionnelle', desc: 'Minimum 2 ans d\'expérience professionnelle requise pour le MBA INSEAD' },
      { titre: 'GMAT/GRE', desc: 'Score GMAT minimum autour de 700 pour être compétitif' },
    ],
  },

  // ─── CANADA ────────────────────────────────────────────────────────────────

  {
    nom: 'Bourse d\'excellence Vanier (Canada)',
    organisme: 'Gouvernement du Canada',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Doctorat',
    domaine: 'Tous domaines',
    montant: '50 000 CAD/an (3 ans)',
    deadline: '2027-11-01',
    date_debut: '2027-08-01',
    duree: '3 ans',
    type_financement: 'Complète',
    description: 'L\'une des bourses les plus prestigieuses du Canada pour les doctorants étrangers. Critères : excellence académique, leadership, potentiel de recherche. Réservé aux étudiants inscrits dans une université canadienne.',
    lien: 'https://vanier.gc.ca/en/home-accueil.html',
    avantages: ['50 000 CAD/an pendant 3 ans', 'Reconnaissance internationale du titre "Vanier Scholar"', 'Accès au réseau des chercheurs canadiens'],
    documents_requis: ['Dossier de candidature Vanier en ligne', 'Plan de recherche détaillé (5 pages)', 'CV académique complet', 'Trois lettres de recommandation', 'Relevés de notes de toutes les universités fréquentées', 'Preuve d\'inscription en doctorat au Canada', 'Déclaration d\'intérêts de leadership'],
    nationalites_eligibles: ['Tous pays hors Canada'],
    langue_requise: 'Anglais ou Français',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: 167,
    criteres: [
      { titre: 'Inscription en doctorat obligatoire', desc: 'Vous devez être inscrit ou accepté en programme de doctorat dans une université canadienne éligible' },
      { titre: 'Trois critères d\'évaluation', desc: '1) Excellence académique, 2) Potentiel de leadership, 3) Potentiel de recherche' },
      { titre: 'Candidature via l\'université', desc: 'La nomination est faite par l\'université d\'accueil, pas directement par l\'étudiant' },
    ],
  },

  {
    nom: 'Bourses Trudeau',
    organisme: 'Fondation Pierre Elliott Trudeau',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Doctorat',
    domaine: 'Sciences Humaines et Sociales, Droit, Relations Internationales',
    montant: '40 000 CAD/an',
    deadline: '2027-12-01',
    date_debut: '2027-09-01',
    duree: '3 ans',
    type_financement: 'Complète',
    description: 'Soutient les doctorants dont les travaux portent sur les droits humains, la citoyenneté, le pluralisme et la diversité. L\'un des programmes les plus prestige du Canada.',
    lien: 'https://www.trudeaufoundation.ca/programs/fellowships',
    avantages: ['40 000 CAD/an', 'Frais de recherche supplémentaires', 'Mentorat par des leaders', 'Réseau Trudeau exclusif', 'Participation aux Forums Trudeau'],
    documents_requis: ['Projet de thèse complet', 'CV', 'Deux essais (leadership et recherche)', 'Deux lettres de recommandation', 'Transcripts', 'Preuve d\'inscription en doctorat'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Anglais ou Français',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: 16,
    criteres: [
      { titre: 'Engagement social et leadership', desc: 'La Fondation Trudeau recherche des leaders engagés dans des causes sociales' },
      { titre: 'Lien avec les 4 thèmes', desc: 'Droits humains, citoyenneté, pluralisme, environnement' },
    ],
  },

  {
    nom: 'Bourse Université de Montréal – Excellence BIFI',
    organisme: 'Université de Montréal',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '10 000 CAD/an',
    deadline: '2027-02-01',
    date_debut: '2026-11-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Bourse d\'excellence pour étudiants internationaux francophones inscrits en Master à l\'UdeM. Montréal est la deuxième ville francophone du monde.',
    lien: 'https://www.bourse.umontreal.ca',
    avantages: ['10 000 CAD/an', 'Exemption partielle des frais supplémentaires', 'Accès aux services d\'intégration UdeM'],
    documents_requis: ['Formulaire de candidature UdeM', 'CV', 'Lettre de motivation', 'Relevés de notes officiels', 'Deux lettres de recommandation', 'Preuve de maîtrise du français'],
    nationalites_eligibles: ['Tous pays francophones'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Admission UdeM requise', desc: 'Vous devez avoir reçu une lettre d\'admission de l\'Université de Montréal avant de candidater' },
      { titre: 'Moyenne minimale', desc: 'Moyenne cumulée de 3,0/4,3 ou équivalent requis' },
    ],
  },

  {
    nom: 'Bourse Université Laval – Réussite internationale',
    organisme: 'Université Laval',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: 'Exemption droits + 3 000 CAD',
    deadline: '2027-01-15',
    date_debut: '2026-10-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Facilite l\'accès des étudiants étrangers à l\'Université Laval à Québec avec exemption partielle des frais de scolarité supplémentaires.',
    lien: 'https://www.ulaval.ca/international',
    avantages: ['Exemption des droits supplémentaires', 'Aide de 3 000 CAD', 'Accompagnement à l\'intégration', 'Logement en résidence prioritaire'],
    documents_requis: ['Admission Université Laval', 'CV', 'Lettre de motivation', 'Relevés de notes', 'Deux lettres de recommandation'],
    nationalites_eligibles: ['Tous pays francophones d\'Afrique'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Excellente moyenne', desc: 'Moyenne minimale équivalent à 3,0/4,3 à l\'Université Laval' },
    ],
  },

  {
    nom: 'UQAM – Bourse Excellence internationale',
    organisme: 'Université du Québec à Montréal',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Master',
    domaine: 'Arts, Sciences, Communication, Sciences sociales',
    montant: '5 000 – 15 000 CAD',
    deadline: '2027-03-01',
    date_debut: '2026-12-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Programme de bourses d\'excellence pour étudiants internationaux à l\'UQAM. L\'UQAM est reconnue pour ses sciences sociales et ses arts.',
    lien: 'https://bourses.uqam.ca',
    avantages: ['Bourse annuelle variable', 'Réduction des frais de scolarité'],
    documents_requis: ['Dossier d\'admission UQAM', 'CV', 'Lettre de motivation', 'Relevés de notes', 'Lettre de recommandation'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Admission UQAM préalable', desc: 'La bourse est accordée lors de l\'admission en programme de Master' },
    ],
  },

  {
    nom: 'Ontario Graduate Scholarship (OGS)',
    organisme: 'Gouvernement de l\'Ontario',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '15 000 CAD/an',
    deadline: '2027-04-01',
    date_debut: '2027-01-01',
    duree: '1 an renouvelable',
    type_financement: 'Partielle',
    description: 'Bourse provinciale de l\'Ontario pour les étudiants de Master et Doctorat dans les universités ontariennes. Critères académiques élevés.',
    lien: 'https://osap.gov.on.ca',
    avantages: ['15 000 CAD/an', 'Éligible aux universités de Toronto, Ottawa, McMaster, etc.'],
    documents_requis: ['Formulaire OGS en ligne', 'CV', 'Relevés de notes', 'Deux lettres de recommandation', 'Lettre d\'intention de recherche'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Anglais ou Français',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Inscription dans une université ontarienne', desc: 'Universités de Toronto, Ottawa, Queen\'s, McMaster, etc.' },
      { titre: 'Moyenne A- minimum', desc: 'Équivalent à 3,7/4,0 dans la plupart des systèmes de notation' },
    ],
  },

  {
    nom: 'MITACS Globalink Research Award',
    organisme: 'MITACS',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Master',
    domaine: 'Sciences, Technologie, Ingénierie, Mathématiques',
    montant: '6 000 CAD (12 semaines)',
    deadline: '2027-09-01',
    date_debut: '2027-06-01',
    duree: '3 mois',
    type_financement: 'Complète',
    description: 'Stage de recherche de 12 semaines dans une université canadienne pour étudiants internationaux. Non pas une bourse d\'études complète mais un financement de stage.',
    lien: 'https://www.mitacs.ca/en/programs/globalink/globalink-research-internship',
    avantages: ['6 000 CAD pour 12 semaines', 'Billet d\'avion', 'Logement', 'Frais de visa remboursés'],
    documents_requis: ['Formulaire MITACS en ligne', 'CV', 'Lettre de motivation', 'Relevés de notes récents', 'Lettre de recommandation d\'un professeur', 'Preuve de niveau d\'anglais'],
    nationalites_eligibles: ['Pays partenaires MITACS (incluant plusieurs pays africains)'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: 500,
    criteres: [
      { titre: 'Étudiant en cours d\'études', desc: 'Vous devez être inscrit en Licence 3, Master ou Doctorat au moment du stage' },
      { titre: 'Projet de recherche spécifique', desc: 'Vous choisissez un projet parmi ceux proposés par les universités canadiennes' },
    ],
  },

  {
    nom: 'Bourse de la Francophonie Canadienne',
    organisme: 'Fédération des communautés francophones',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Master',
    domaine: 'Tous domaines francophones',
    montant: '8 000 CAD',
    deadline: '2027-05-15',
    date_debut: '2027-02-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'Encourage la mobilité étudiante francophone vers le Canada hors Québec (Ontario, Nouveau-Brunswick, Manitoba, etc.) pour valoriser les communautés francophones canadiennes.',
    lien: 'https://www.fcfa.ca',
    avantages: ['8 000 CAD', 'Accès aux communautés francophones hors Québec'],
    documents_requis: ['Formulaire FCFA', 'CV', 'Lettre de motivation en français', 'Relevés de notes', 'Deux références'],
    nationalites_eligibles: ['Pays francophones d\'Afrique subsaharienne', 'Maghreb', 'Haïti'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 35,
    nb_places: null,
    criteres: [
      { titre: 'Études hors Québec', desc: 'L\'université d\'accueil doit être dans une province canadienne autre que le Québec' },
    ],
  },

  {
    nom: 'McGill University – Bourses internationales',
    organisme: 'Université McGill',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Doctorat',
    domaine: 'Médecine, Sciences de la Santé, Biologie',
    montant: '25 000 CAD/an',
    deadline: '2027-01-31',
    date_debut: '2026-10-01',
    duree: '3 à 4 ans',
    type_financement: 'Partielle',
    description: 'Financement de recherche doctorale en sciences de la santé à l\'Université McGill, classée top 30 mondiale.',
    lien: 'https://www.mcgill.ca/students/scholarships',
    avantages: ['25 000 CAD/an', 'Accès aux laboratoires McGill', 'Couverture santé'],
    documents_requis: ['Dossier d\'admission McGill', 'Projet de recherche (8 pages)', 'CV académique', 'Trois lettres de recommandation de chercheurs', 'Relevés de notes complets', 'Publications (si disponibles)'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Directeur de thèse confirmé', desc: 'Vous devez avoir un accord écrit d\'un professeur McGill pour diriger votre thèse' },
    ],
  },

  {
    nom: 'Bourses d\'exemption – Université de Sherbrooke',
    organisme: 'Université de Sherbrooke',
    pays: 'Canada', code_pays: 'ca',
    niveau: 'Master',
    domaine: 'Ingénierie, Sciences, Informatique',
    montant: 'Exemption droits de scolarité supplémentaires',
    deadline: '2027-03-15',
    date_debut: '2026-12-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Exonération des droits de scolarité supplémentaires pour étudiants internationaux admis en sciences et ingénierie. Permet d\'étudier presque au même coût qu\'un étudiant québécois.',
    lien: 'https://www.usherbrooke.ca/international',
    avantages: ['Exemption des frais supplémentaires (≈ 10 000 CAD/an)', 'Accès au programme co-op (stages rémunérés)'],
    documents_requis: ['Admission Université de Sherbrooke', 'CV', 'Relevés de notes', 'Lettre de motivation'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Admission en sciences/ingénierie', desc: 'La bourse est réservée aux programmes de sciences, génie ou informatique' },
    ],
  },

  // ─── BELGIQUE ──────────────────────────────────────────────────────────────

  {
    nom: 'ARES – Bourses de développement',
    organisme: 'Académie de Recherche et d\'Enseignement Supérieur',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Master',
    domaine: 'Développement, Sciences, Ingénierie, Santé, Agriculture',
    montant: '900 €/mois + frais de scolarité',
    deadline: '2027-02-01',
    date_debut: '2026-09-01',
    duree: '1 à 2 ans',
    type_financement: 'Complète',
    description: 'Bourses pour étudiants africains souhaitant réaliser un master spécialisé dans les universités belges. L\'ARES couvre les frais de scolarité, l\'allocation mensuelle, le billet d\'avion et l\'assurance.',
    lien: 'https://www.ares-ac.be/fr/cooperation-au-developpement/bourses',
    avantages: ['Frais de scolarité couverts', 'Allocation mensuelle (900 €)', 'Billet d\'avion aller-retour', 'Assurance maladie', 'Frais d\'installation (750 €)', 'Accès à la bibliothèque numérique ARES'],
    documents_requis: ['Formulaire ARES en ligne', 'Copie du diplôme de Licence (apostillé)', 'Relevés de notes des 3 années de Licence', 'CV', 'Lettre de motivation (2 pages)', 'Deux lettres de recommandation académiques', 'Justificatif de situation professionnelle actuelle', 'Passeport', 'Certification de français (DELF B2 minimum)'],
    nationalites_eligibles: ['Bénin', 'Burkina Faso', 'Burundi', 'Cameroun', 'Congo RDC', 'Côte d\'Ivoire', 'Éthiopie', 'Haïti', 'Kenya', 'Madagascar', 'Mali', 'Maroc', 'Mozambique', 'Niger', 'Ouganda', 'Rwanda', 'Sénégal', 'Tanzanie', 'Togo'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 40,
    nb_places: 70,
    criteres: [
      { titre: 'Pays éligibles spécifiques', desc: 'Uniquement les pays listés par l\'ARES sont éligibles. Vérifiez la liste complète sur le site ARES.' },
      { titre: 'Retour dans le pays d\'origine', desc: 'Engagement de retour dans le pays d\'origine après les études pour contribuer au développement local' },
      { titre: 'Pas d\'autre bourse en cours', desc: 'Le candidat ne doit pas bénéficier d\'une autre bourse de développement au moment de la candidature' },
    ],
  },

  {
    nom: 'Bourse WBI – Wallonie-Bruxelles International',
    organisme: 'WBI',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '750 – 1 050 €/mois',
    deadline: '2027-02-28',
    date_debut: '2026-11-01',
    duree: '1 an renouvelable',
    type_financement: 'Partielle',
    description: 'Bourses de mobilité entrante pour étudiants des pays partenaires souhaitant étudier en Wallonie ou à Bruxelles. Ouverte aux étudiants francophones.',
    lien: 'https://www.wbi.be/fr/bourses',
    avantages: ['Allocation mensuelle (750-1 050 €)', 'Accueil et accompagnement', 'Accès aux activités WBI'],
    documents_requis: ['Formulaire WBI en ligne', 'CV', 'Lettre de motivation', 'Diplôme de Licence', 'Relevés de notes', 'Deux lettres de recommandation', 'Passeport', 'Preuve de niveau de français'],
    nationalites_eligibles: ['Pays partenaires de la Wallonie et de Bruxelles en Afrique francophone'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B1',
    age_max: 35,
    nb_places: null,
    criteres: [
      { titre: 'Programme accrédité en Belgique', desc: 'Le programme de Master doit être reconnu par la Fédération Wallonie-Bruxelles' },
    ],
  },

  {
    nom: 'VLIR-UOS – Bourses Master complet',
    organisme: 'VLIR-UOS (Flandre)',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Master',
    domaine: 'Développement durable, Santé publique, Agriculture, Environnement',
    montant: 'Bourse complète (frais de vie + scolarité)',
    deadline: '2027-02-01',
    date_debut: '2026-11-01',
    duree: '1 à 2 ans',
    type_financement: 'Complète',
    description: 'Masters spécialisés avec bourse complète dans les universités flamandes belges (KU Leuven, Ghent, etc.) pour étudiants des pays en développement.',
    lien: 'https://www.vliruos.be/en/scholarships',
    avantages: ['Frais de scolarité 100%', 'Allocation mensuelle complète', 'Billet d\'avion', 'Assurance', 'Frais d\'installation'],
    documents_requis: ['Formulaire VLIR-UOS en ligne', 'Diplôme de Licence', 'Relevés de notes', 'CV', 'Lettre de motivation', 'Deux lettres de recommandation', 'Certification de langue (anglais B2)', 'Passeport'],
    nationalites_eligibles: ['Bénin', 'Bolivie', 'Burkina Faso', 'Burundi', 'Cambodge', 'Cameroun', 'Congo RDC', 'Cuba', 'Éthiopie', 'Haïti', 'Kenya', 'Madagascar', 'Mali', 'Mozambique', 'Niger', 'Sénégal', 'Rwanda', 'Tanzanie', 'Togo', 'Ouganda'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: 40,
    nb_places: 60,
    criteres: [
      { titre: 'Programmes VLIR-UOS spécifiques', desc: 'Candidature uniquement pour les programmes ICP (International Course Programme) listés sur le site VLIR' },
      { titre: 'Engagement de retour', desc: 'Engagement de retour dans le pays d\'origine pour contribuer au développement' },
    ],
  },

  {
    nom: 'UCLouvain – Bourse Excellence internationale',
    organisme: 'UCLouvain',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: 'Jusqu\'à 8 000 €/an',
    deadline: '2027-03-01',
    date_debut: '2026-12-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Bourse pour les meilleurs étudiants internationaux admis dans les programmes de Master à l\'UCLouvain, l\'une des meilleures universités catholiques du monde.',
    lien: 'https://uclouvain.be/fr/etudier/bourses-et-financements.html',
    avantages: ['Aide financière annuelle (jusqu\'à 8 000 €)', 'Logement en résidence prioritaire', 'Accès aux ressources universitaires'],
    documents_requis: ['Dossier d\'admission UCLouvain', 'CV', 'Lettre de motivation', 'Relevés de notes', 'Diplôme', 'Deux lettres de recommandation'],
    nationalites_eligibles: ['Tous pays hors Belgique'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Excellence académique', desc: 'Attribution automatique aux meilleurs dossiers d\'admission' },
    ],
  },

  {
    nom: 'ULB – Bourse Excellence étudiants africains',
    organisme: 'Université Libre de Bruxelles',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Master',
    domaine: 'Sciences Politiques, Droit, Sciences Sociales',
    montant: '800 €/mois',
    deadline: '2027-04-30',
    date_debut: '2027-01-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Financement partiel pour étudiants subsahariens admis en Master à l\'ULB, université au cœur de Bruxelles, capitale de l\'Europe.',
    lien: 'https://www.ulb.be/fr/candidature-et-inscription/bourses-d-etudes',
    avantages: ['800 €/mois', 'Accès aux activités culturelles ULB', 'Mentorat par des alumni africains'],
    documents_requis: ['Formulaire ULB', 'CV', 'Lettre de motivation', 'Relevés de notes', 'Diplôme de Licence', 'Deux lettres de recommandation', 'Certification de français'],
    nationalites_eligibles: ['Afrique subsaharienne francophone'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 35,
    nb_places: null,
    criteres: [],
  },

  {
    nom: 'Bourse Fondation Roi Baudouin',
    organisme: 'Fondation Roi Baudouin',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Master',
    domaine: 'Développement humain, Société civile, Droit',
    montant: '1 000 €/mois',
    deadline: '2027-06-01',
    date_debut: '2027-03-01',
    duree: '1 à 2 ans',
    type_financement: 'Partielle',
    description: 'Soutient des projets et études liés au développement humain dans les pays africains francophones. Priorité aux candidats avec engagement associatif.',
    lien: 'https://www.kbs-frb.be/fr/Activities/Grants',
    avantages: ['1 000 €/mois', 'Mentorat personnalisé', 'Accès au réseau de la Fondation'],
    documents_requis: ['Formulaire en ligne', 'CV', 'Lettre de motivation avec projet de retour', 'Relevés de notes', 'Deux lettres de recommandation', 'Preuve d\'engagement associatif ou civique'],
    nationalites_eligibles: ['Afrique subsaharienne francophone'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 35,
    nb_places: null,
    criteres: [
      { titre: 'Engagement social requis', desc: 'Candidats avec expérience dans des associations, ONG ou projets communautaires valorisés' },
    ],
  },

  {
    nom: 'Bourse Université de Liège – Coopération Sud',
    organisme: 'Université de Liège',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Master',
    domaine: 'Sciences, Ingénierie, Vétérinaire, Médecine',
    montant: '800 €/mois',
    deadline: '2027-04-15',
    date_debut: '2027-01-15',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Programme de coopération académique de l\'ULiège ciblant les étudiants d\'Afrique subsaharienne francophone dans les domaines scientifiques.',
    lien: 'https://www.uliege.be/cms/c_9054472/fr/international',
    avantages: ['800 €/mois', 'Exemption partielle des frais', 'Accès aux labos de recherche ULiège'],
    documents_requis: ['Formulaire ULiège', 'CV', 'Lettre de motivation', 'Relevés de notes officiels', 'Diplôme', 'Deux lettres de recommandation académiques'],
    nationalites_eligibles: ['Afrique subsaharienne francophone'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B2',
    age_max: 35,
    nb_places: null,
    criteres: [],
  },

  {
    nom: 'Bourse CAES – Fédération Wallonie-Bruxelles',
    organisme: 'Fédération Wallonie-Bruxelles',
    pays: 'Belgique', code_pays: 'be',
    niveau: 'Licence',
    domaine: 'Tous domaines',
    montant: '600 €/mois',
    deadline: '2027-06-30',
    date_debut: '2027-03-01',
    duree: '1 an renouvelable',
    type_financement: 'Partielle',
    description: 'Aides sociales aux étudiants étrangers inscrits dans les établissements d\'enseignement supérieur en Fédération Wallonie-Bruxelles en situation de besoin.',
    lien: 'https://www.enseignement.be',
    avantages: ['600 €/mois', 'Accès aux infrastructures sociales universitaires'],
    documents_requis: ['Inscription universitaire', 'Justificatif de ressources', 'Passeport', 'Titre de séjour'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Français',
    niveau_langue_requis: 'B1',
    age_max: 30,
    nb_places: null,
    criteres: [
      { titre: 'Critères sociaux', desc: 'Attribution basée sur les revenus et la situation sociale du candidat' },
    ],
  },

  // ─── ALLEMAGNE ────────────────────────────────────────────────────────────

  {
    nom: 'DAAD – Bourse Programme Afrique',
    organisme: 'DAAD (Office Allemand d\'Échanges Académiques)',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '861 €/mois + avantages',
    deadline: '2027-10-15',
    date_debut: '2027-07-15',
    duree: '1 à 2 ans',
    type_financement: 'Complète',
    description: 'Bourses pour étudiants africains souhaitant poursuivre un Master ou Doctorat en Allemagne. Nombreux programmes disponibles en anglais. L\'allemand n\'est pas toujours obligatoire.',
    lien: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
    avantages: ['Allocation mensuelle (861 €)', 'Assurance maladie, accident et responsabilité civile', 'Allocation voyage (aller-retour)', 'Aide au logement', 'Cours de langue allemande', 'Subvention matériel (52 €/mois)'],
    documents_requis: ['Formulaire DAAD en ligne', 'CV en allemand ou anglais', 'Lettre de motivation', 'Copies certifiées de tous diplômes', 'Relevés de notes officiels', 'Deux lettres de recommandation académiques', 'Projet d\'études en Allemagne', 'Passeport', 'Certificat de langue (IELTS B2 ou TestDaF si programme en allemand)'],
    nationalites_eligibles: ['Tous pays d\'Afrique subsaharienne', 'Maghreb'],
    langue_requise: 'Anglais ou Allemand selon le programme',
    niveau_langue_requis: 'B2',
    age_max: 32,
    nb_places: null,
    criteres: [
      { titre: 'Diplôme récent', desc: 'Le diplôme de Licence ne doit pas dater de plus de 6 ans au moment de la candidature' },
      { titre: 'Admission préalable conseillée', desc: 'Avoir une admission (ou au moins une candidature en cours) dans une université allemande renforce le dossier' },
    ],
  },

  {
    nom: 'Bourse Heinrich Böll Stiftung',
    organisme: 'Fondation Heinrich Böll',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Sciences sociales, Environnement, Écologie, Droits humains',
    montant: '850 €/mois + prime matériel',
    deadline: '2027-09-01',
    date_debut: '2027-04-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Bourse de la fondation politique verte allemande pour des profils engagés en environnement, démocratie et droits humains. Valorise l\'engagement politique et social.',
    lien: 'https://www.boell.de/en/foundation/scholarships',
    avantages: ['Allocation mensuelle (850 €)', 'Prime matériel (300 €/an)', 'Séminaires politiques et académiques', 'Réseau de boursiers engagés'],
    documents_requis: ['Dossier en ligne Heinrich Böll', 'CV', 'Lettre de motivation avec engagement politique/social', 'Relevés de notes', 'Deux lettres de recommandation', 'Certificat de langue (allemand ou anglais B2)'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Allemand ou Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Engagement écologique et social', desc: 'Priorité aux candidats actifs dans des causes environnementales ou sociales' },
      { titre: 'Valeurs de la fondation', desc: 'Partage des valeurs démocratiques, écologiques et des droits humains' },
    ],
  },

  {
    nom: 'Bourse Friedrich Ebert Stiftung',
    organisme: 'Fondation Friedrich Ebert',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Sciences Politiques, Économie, Droit, Sciences Sociales',
    montant: '850 €/mois',
    deadline: '2027-06-30',
    date_debut: '2027-03-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Bourse de la fondation sociale-démocrate allemande. Priorité aux étudiants engagés dans les mouvements sociaux, syndicaux ou politiques progressistes.',
    lien: 'https://www.fes.de/en/scholarships',
    avantages: ['Allocation mensuelle (850 €)', 'Accès aux séminaires politiques', 'Réseau international FES'],
    documents_requis: ['Formulaire FES', 'CV', 'Lettre de motivation avec engagement social', 'Relevés de notes', 'Deux lettres de recommandation', 'Attestation d\'engagement associatif ou syndical'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Allemand',
    niveau_langue_requis: 'B1',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Engagement social-démocrate', desc: 'Actif dans des mouvements syndicaux, politiques ou associatifs progressistes' },
    ],
  },

  {
    nom: 'Bourse Konrad Adenauer Stiftung',
    organisme: 'Fondation Konrad Adenauer',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Droit, Sciences Politiques, Économie, Sciences Sociales',
    montant: '850 – 1 200 €/mois',
    deadline: '2027-07-15',
    date_debut: '2027-03-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Bourse pour étudiants avec excellent dossier académique et engagement démocratique chrétien-démocrate. L\'une des six grandes fondations politiques allemandes.',
    lien: 'https://www.kas.de/en/web/stipendien',
    avantages: ['Allocation mensuelle (850-1 200 €)', 'Séminaires académiques', 'Réseau politique KAS international'],
    documents_requis: ['Formulaire KAS en ligne', 'CV', 'Lettre de motivation', 'Relevés de notes', 'Deux lettres de recommandation', 'Essai sur valeurs démocratiques', 'Certificat de langue'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Allemand ou Anglais',
    niveau_langue_requis: 'B1',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Valeurs démocratiques chrétiennes-démocrates', desc: 'Partage des valeurs de la démocratie chrétienne-démocrate' },
      { titre: 'Engagement civique', desc: 'Actif dans des associations, partis ou organisations civiques' },
    ],
  },

  {
    nom: 'Bourse Alexander von Humboldt',
    organisme: 'Fondation Alexander von Humboldt',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Doctorat',
    domaine: 'Recherche scientifique (tous domaines)',
    montant: '2 500 €/mois',
    deadline: '2027-10-15',
    date_debut: '2027-01-01',
    duree: '6 à 24 mois',
    type_financement: 'Complète',
    description: 'Pour jeunes chercheurs (post-doctorants) souhaitant mener des recherches en Allemagne dans n\'importe quelle discipline. Très compétitif et très prestigieux. Candidature possible à tout moment.',
    lien: 'https://www.humboldt-foundation.de/en/apply/sponsorship-programmes/humboldt-research-fellowship',
    avantages: ['2 500 €/mois', 'Billet d\'avion', 'Couverture sociale complète', 'Cours d\'allemand', 'Aide à la famille (conjoint + enfants)', 'Soutien au retour dans le pays d\'origine'],
    documents_requis: ['Formulaire Humboldt en ligne', 'CV académique complet avec liste de publications', 'Projet de recherche détaillé (5 pages)', 'Invitation d\'un hôte académique en Allemagne', 'Trois lettres de recommandation', 'Copies des publications'],
    nationalites_eligibles: ['Tous pays hors Allemagne'],
    langue_requise: 'Allemand ou Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Post-doctorat', desc: 'Destiné aux chercheurs ayant obtenu leur doctorat il y a moins de 12 ans' },
      { titre: 'Publications requises', desc: 'Un historique de publications dans des revues à comité de lecture est pratiquement indispensable' },
      { titre: 'Hôte en Allemagne', desc: 'Vous devez avoir un accord préalable avec un professeur ou laboratoire en Allemagne' },
    ],
  },

  {
    nom: 'Bourse TU Berlin – Africa Initiative',
    organisme: 'TU Berlin',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Ingénierie, Technologie, Urbanisme, Architecture',
    montant: 'Exemption frais + 500 €/mois',
    deadline: '2027-03-15',
    date_debut: '2026-12-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Programme spécial de la TU Berlin (top 10 universités techniques mondiales) pour étudiants africains en ingénierie et technologie.',
    lien: 'https://www.tu.berlin/international',
    avantages: ['Exemption des frais de scolarité', 'Allocation mensuelle (500 €)', 'Accès aux labos TU Berlin'],
    documents_requis: ['Dossier d\'admission TU Berlin', 'CV', 'Lettre de motivation', 'Relevés de notes', 'Diplôme', 'Certification de langue (anglais B2)', 'Lettre de recommandation'],
    nationalites_eligibles: ['Afrique subsaharienne'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: 30,
    nb_places: 20,
    criteres: [
      { titre: 'Admission TU Berlin requise', desc: 'Vous devez être admis dans un programme de Master à la TU Berlin' },
    ],
  },

  {
    nom: 'Bourse Rosa Luxemburg Stiftung',
    organisme: 'Fondation Rosa Luxemburg',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Sciences Sociales, Économie critique, Études de genre',
    montant: '850 €/mois',
    deadline: '2027-09-15',
    date_debut: '2027-04-15',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'Fondation progressiste promouvant l\'égalité sociale et la démocratie. Ouverte aux étudiants du Sud global avec engagement politique de gauche.',
    lien: 'https://www.rosalux.de/en/scholarships',
    avantages: ['Allocation mensuelle (850 €)', 'Séminaires politiques internationaux', 'Réseau mondial Rosa Luxemburg'],
    documents_requis: ['Formulaire en ligne', 'CV', 'Lettre de motivation politique', 'Relevés de notes', 'Deux lettres de recommandation', 'Essai sur engagement politique'],
    nationalites_eligibles: ['Tous pays du Sud global'],
    langue_requise: 'Allemand ou Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Engagement politique de gauche', desc: 'Actif dans des mouvements progressistes, féministes, anti-racistes ou écologistes' },
    ],
  },

  {
    nom: 'Bourse Studienstiftung des deutschen Volkes',
    organisme: 'Fondation nationale allemande de bourses',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '850 €/mois + prime livre',
    deadline: '2027-12-01',
    date_debut: '2027-08-01',
    duree: '2 ans',
    type_financement: 'Partielle',
    description: 'La plus grande organisation de bourses d\'études en Allemagne. Très sélective et très prestigieuse. Candidature uniquement par nomination d\'un professeur ou établissement.',
    lien: 'https://www.studienstiftung.de/en/scholarship/application/',
    avantages: ['Allocation mensuelle (850 €)', 'Prime livres (300 €/an)', 'Résidences d\'été', 'Réseau académique d\'élite'],
    documents_requis: ['Nomination par un professeur ou établissement (obligatoire)', 'CV', 'Deux essais', 'Relevés de notes', 'Projets et réalisations académiques'],
    nationalites_eligibles: ['Tous pays hors Allemagne (pour étudiants en Allemagne)'],
    langue_requise: 'Allemand',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Nomination obligatoire', desc: 'Vous ne pouvez pas candidater directement. Un professeur ou un établissement doit vous nommer.' },
      { titre: 'Excellence absolue', desc: 'Réservé aux 0,5% des meilleurs étudiants d\'Allemagne' },
    ],
  },

  {
    nom: 'DAAD – Scholarships for Development',
    organisme: 'DAAD',
    pays: 'Allemagne', code_pays: 'de',
    niveau: 'Master',
    domaine: 'Développement, Agriculture, Eau, Santé, Infrastructure',
    montant: '861 €/mois + avantages',
    deadline: '2027-09-30',
    date_debut: '2027-06-30',
    duree: '1 à 2 ans',
    type_financement: 'Complète',
    description: 'Programme DAAD dédié au développement avec focus sur des domaines prioritaires pour les pays en développement. Très adapté aux étudiants africains souhaitant contribuer au développement local.',
    lien: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/development-related/',
    avantages: ['Allocation complète (861 €/mois)', 'Billet d\'avion', 'Assurance complète', 'Aide logement', 'Cours d\'allemand'],
    documents_requis: ['Formulaire DAAD développement', 'CV', 'Lettre de motivation orientée développement', 'Plan de retour dans le pays', 'Relevés de notes', 'Deux lettres de recommandation', 'Passeport'],
    nationalites_eligibles: ['Tous pays en développement d\'Afrique subsaharienne'],
    langue_requise: 'Anglais ou Allemand',
    niveau_langue_requis: 'B2',
    age_max: 36,
    nb_places: null,
    criteres: [
      { titre: 'Domaine développement', desc: 'Le Master doit être dans un domaine directement lié au développement' },
      { titre: 'Plan de retour', desc: 'Un plan concret de retour et de contribution au développement du pays est obligatoire' },
    ],
  },

  // ─── ROYAUME-UNI ──────────────────────────────────────────────────────────

  {
    nom: 'Bourse Chevening',
    organisme: 'Foreign, Commonwealth & Development Office (FCDO)',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: 'Couverture totale (frais de vie + scolarité)',
    deadline: '2027-11-07',
    date_debut: '2027-08-01',
    duree: '1 an',
    type_financement: 'Complète',
    description: 'Programme phare du gouvernement britannique. L\'une des bourses les plus prestigieuses au monde. Ouverte aux futurs leaders internationaux. Couvre 100% des frais.',
    lien: 'https://www.chevening.org/apply/',
    avantages: ['Frais de scolarité 100%', 'Allocation mensuelle complète (≈ 1 300 £/mois à Londres)', 'Billet d\'avion aller-retour', 'Allocation arrivée', 'Assurance maladie NHS', 'Frais de visa et test tuberculose', 'Accès au réseau Chevening (50 000+ alumni)'],
    documents_requis: ['Formulaire Chevening en ligne', 'CV en anglais', 'Quatre essais de motivation', 'Diplôme de Licence', 'Relevés de notes officiels', 'Deux lettres de recommandation de personnalités', 'IELTS 6.5 minimum', 'Passeport', 'Lettre d\'admission de 3 universités britanniques (non requise au moment de la candidature)'],
    nationalites_eligibles: ['Pays éligibles Chevening (liste sur le site officiel)'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: 1800,
    criteres: [
      { titre: 'Potentiel de leadership', desc: 'Chevening recherche des futurs leaders. Engagement et réalisations sont aussi importants que les notes.' },
      { titre: '2 ans d\'expérience professionnelle', desc: 'Minimum 2 ans d\'expérience de travail (à temps plein) avant la candidature' },
      { titre: 'Admission dans 3 universités UK', desc: 'Vous devez obtenir une admission dans au moins une des 3 universités listées avant juillet' },
    ],
  },

  {
    nom: 'Bourse Commonwealth',
    organisme: 'Commonwealth Scholarship Commission',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Santé, Éducation, Sciences, Technologies, Agriculture',
    montant: 'Bourse complète',
    deadline: '2027-10-26',
    date_debut: '2027-07-01',
    duree: '1 an',
    type_financement: 'Complète',
    description: 'Bourses pour étudiants des pays du Commonwealth voulant obtenir un Master au Royaume-Uni. Focus sur le développement et l\'impact dans le pays d\'origine.',
    lien: 'https://cscuk.fcdo.gov.uk/apply/',
    avantages: ['Frais de scolarité 100%', 'Allocation mensuelle', 'Billet d\'avion', 'Allocation arrivée', 'Assurance', 'Aide thèse'],
    documents_requis: ['Formulaire CSC en ligne', 'CV', 'Déclaration d\'impact dans le pays d\'origine', 'Deux essais', 'Trois lettres de recommandation', 'Relevés de notes', 'IELTS 6.0 minimum', 'Passeport'],
    nationalites_eligibles: ['Pays membres du Commonwealth d\'Afrique subsaharienne'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Pays du Commonwealth', desc: 'Votre pays doit être membre du Commonwealth (Nigeria, Ghana, Kenya, Sierra Leone, etc.)' },
      { titre: 'Plan d\'impact', desc: 'Déclaration obligatoire sur comment vous contribuerez au développement de votre pays après les études' },
    ],
  },

  {
    nom: 'Oxford – Weidenfeld-Hoffmann Trust',
    organisme: 'Université d\'Oxford',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Sciences Politiques, Économie, Droit, Relations Internationales',
    montant: 'Bourse complète',
    deadline: '2027-01-23',
    date_debut: '2026-10-01',
    duree: '1 à 2 ans',
    type_financement: 'Complète',
    description: 'Bourse pour leaders émergents de pays en développement souhaitant étudier à Oxford. L\'une des meilleures universités mondiales.',
    lien: 'https://www.whtrust.org',
    avantages: ['Frais de scolarité Oxford 100%', 'Allocation mensuelle complète', 'Programme de leadership annuel', 'Accès au réseau Oxford mondial'],
    documents_requis: ['Dossier d\'admission Oxford', 'CV', 'Essais personnels Oxford', 'Deux à trois lettres de recommandation', 'IELTS 7.0 ou TOEFL 110', 'Relevés de notes certifiés', 'Déclaration d\'impact social'],
    nationalites_eligibles: ['Pays en développement (incluant Afrique subsaharienne)'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: 35,
    criteres: [
      { titre: 'Admission Oxford préalable', desc: 'Vous devez d\'abord obtenir une admission à Oxford pour être éligible à la bourse' },
      { titre: 'Potentiel de leadership exceptionnel', desc: 'Priorité aux candidats avec un potentiel de leadership clair et un projet de changement social' },
    ],
  },

  {
    nom: 'Bourse Gates Cambridge',
    organisme: 'Université de Cambridge',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Doctorat',
    domaine: 'Tous domaines',
    montant: 'Bourse complète (≈ 20 000 £/an)',
    deadline: '2027-12-03',
    date_debut: '2027-09-01',
    duree: '3 ans',
    type_financement: 'Complète',
    description: 'L\'une des bourses les plus compétitives et prestigieuses du monde. Financée par la Fondation Bill & Melinda Gates. Réservée aux meilleurs esprits mondiaux souhaitant étudier à Cambridge.',
    lien: 'https://www.gatescambridge.org/apply/',
    avantages: ['Frais de scolarité Cambridge 100%', '≈ 20 000 £/an pour les frais de vie', 'Voyage d\'avion annuel', 'Financement recherche', 'Réseau Gates Cambridge exclusif'],
    documents_requis: ['Dossier d\'admission Cambridge complet', 'CV académique exceptionnel', 'Projet de recherche (détaillé)', 'Trois lettres de recommandation de chercheurs reconnus', 'Publications ou travaux de recherche', 'IELTS 7.5 ou TOEFL 115', 'Essai sur contribution au monde'],
    nationalites_eligibles: ['Tous pays hors Royaume-Uni'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: 90,
    criteres: [
      { titre: 'Excellence académique absolue', desc: 'Réservé aux meilleurs candidats mondiaux. Moyenne proche de la perfection et publications attendues.' },
      { titre: 'Admission Cambridge d\'abord', desc: 'L\'admission à Cambridge est évaluée indépendamment de la bourse' },
    ],
  },

  {
    nom: 'UK Global Talent Visa – GREAT Scholarship',
    organisme: 'British Council',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'STEM, Agriculture, Santé, Développement',
    montant: '10 000 £ (partiel)',
    deadline: '2027-04-30',
    date_debut: '2027-01-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'Bourse du British Council pour les étudiants de pays en développement souhaitant étudier dans des universités britanniques partenaires. Multiple pays africains éligibles.',
    lien: 'https://www.britishcouncil.org/study-work-abroad/in-uk/great-scholarship',
    avantages: ['10 000 £ sur les frais de scolarité', 'Accès au réseau British Council', 'Accompagnement administratif'],
    documents_requis: ['Formulaire British Council', 'CV', 'Lettre de motivation', 'Admission dans une université partenaire UK', 'IELTS 6.0', 'Relevés de notes', 'Passeport'],
    nationalites_eligibles: ['Ghana', 'Kenya', 'Nigeria', 'Sénégal', 'Afrique du Sud', 'Tanzanie', 'Ouganda', 'Éthiopie', 'Rwanda'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Pays éligibles spécifiques', desc: 'Vérifiez sur le site British Council si votre pays est dans la liste des pays éligibles pour l\'année en cours' },
      { titre: 'Admission dans une université partenaire', desc: 'L\'université d\'accueil doit être partenaire du programme GREAT Scholarship' },
    ],
  },

  {
    nom: 'Bourse Edinburgh Global – Research',
    organisme: 'Université d\'Édimbourg',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Doctorat',
    domaine: 'Recherche scientifique, Sciences Sociales, Médecine',
    montant: '15 000 £/an',
    deadline: '2027-03-31',
    date_debut: '2026-12-01',
    duree: '3 ans',
    type_financement: 'Partielle',
    description: 'Programme de bourses de l\'Université d\'Édimbourg (top 20 mondial) pour doctorants internationaux en recherche.',
    lien: 'https://www.ed.ac.uk/student-funding/postgraduate/international',
    avantages: ['Réduction de 15 000 £/an des frais', 'Accès aux labos de recherche Édimbourg'],
    documents_requis: ['Dossier d\'admission Édimbourg', 'Projet de recherche', 'CV académique', 'Deux lettres de recommandation', 'Relevés de notes', 'IELTS 6.5', 'Accord d\'un directeur de thèse'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Directeur de thèse à Édimbourg', desc: 'Accord préalable d\'un professeur de l\'Université d\'Édimbourg nécessaire' },
    ],
  },

  {
    nom: 'Bourse UCL Global',
    organisme: 'University College London',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '5 000 – 15 000 £',
    deadline: '2027-03-27',
    date_debut: '2026-12-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'Bourses partielles pour étudiants internationaux admis dans les programmes de Master à UCL (classé top 10 mondial). Plusieurs catégories de bourses.',
    lien: 'https://www.ucl.ac.uk/scholarships',
    avantages: ['Réduction des frais de scolarité (5 000-15 000 £)', 'Accès au réseau UCL mondial'],
    documents_requis: ['Admission UCL préalable', 'CV', 'Essai personnel', 'Deux lettres de recommandation', 'IELTS 6.5', 'Relevés de notes'],
    nationalites_eligibles: ['Tous pays'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Admission UCL préalable', desc: 'La bourse ne peut être demandée qu\'après avoir reçu une offre d\'admission UCL' },
    ],
  },

  {
    nom: 'Bourse King\'s College London – Afrique',
    organisme: 'King\'s College London',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Santé, Médecine, Droit, Science Politique',
    montant: '10 000 – 20 000 £',
    deadline: '2027-05-01',
    date_debut: '2027-02-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'Programme de bourses de King\'s College London pour étudiants africains exceptionnels dans les domaines de la santé et des sciences sociales.',
    lien: 'https://www.kcl.ac.uk/scholarships',
    avantages: ['10 000-20 000 £ de réduction sur frais', 'Accès au réseau King\'s Alumni Afrique'],
    documents_requis: ['Admission KCL', 'CV', 'Lettre de motivation', 'Deux lettres de recommandation', 'IELTS 6.5', 'Relevés de notes'],
    nationalites_eligibles: ['Afrique subsaharienne'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Admission King\'s College', desc: 'Vous devez d\'abord être admis à King\'s College London' },
    ],
  },

  {
    nom: 'Bourse LSE – Economic Development',
    organisme: 'London School of Economics',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Économie, Développement, Sciences Politiques, Sociologie',
    montant: 'Variable (5 000 – 25 000 £)',
    deadline: '2027-04-23',
    date_debut: '2026-12-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'La LSE est la meilleure école en sciences sociales au monde. Plusieurs bourses pour étudiants des pays en développement.',
    lien: 'https://www.lse.ac.uk/study-at-lse/graduate/fees-and-funding/scholarships-and-bursaries',
    avantages: ['Réduction des frais variable', 'Réseau LSE exceptionnel', 'Accès aux think-tanks et organisations mondiales'],
    documents_requis: ['Dossier d\'admission LSE complet', 'Essais académiques', 'Deux lettres de recommandation de professeurs', 'IELTS 7.0', 'Relevés de notes', 'CV'],
    nationalites_eligibles: ['Pays en développement (incluant Afrique subsaharienne)'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'C1',
    age_max: null,
    nb_places: null,
    criteres: [
      { titre: 'Admission LSE préalable', desc: 'Extrêmement compétitif. L\'admission à la LSE est elle-même très difficile.' },
    ],
  },

  {
    nom: 'Bourse Manchester – Global Development',
    organisme: 'Université de Manchester',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Développement international, Santé publique, Gouvernance',
    montant: '10 000 £',
    deadline: '2027-06-01',
    date_debut: '2027-03-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'Bourse de l\'Université de Manchester pour étudiants de pays en développement dans les domaines du développement international.',
    lien: 'https://www.manchester.ac.uk/study/masters/funding/',
    avantages: ['10 000 £ de réduction', 'Accès aux réseaux de développement international'],
    documents_requis: ['Admission Manchester', 'CV', 'Lettre de motivation', 'Deux lettres de recommandation', 'IELTS 6.5', 'Relevés de notes'],
    nationalites_eligibles: ['Pays en développement d\'Afrique subsaharienne'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [],
  },

  {
    nom: 'Bourse Nottingham – Africa Excellence',
    organisme: 'Université de Nottingham',
    pays: 'Royaume-Uni', code_pays: 'gb',
    niveau: 'Master',
    domaine: 'Tous domaines',
    montant: '8 000 £',
    deadline: '2027-06-15',
    date_debut: '2027-03-01',
    duree: '1 an',
    type_financement: 'Partielle',
    description: 'Bourse pour étudiants africains exceptionnels admis dans les programmes de Master de l\'Université de Nottingham.',
    lien: 'https://www.nottingham.ac.uk/studywithus/international-applicants/scholarships-and-bursaries/',
    avantages: ['8 000 £ de réduction sur les frais'],
    documents_requis: ['Admission Nottingham', 'CV', 'Lettre de motivation', 'Relevés de notes', 'IELTS 6.0'],
    nationalites_eligibles: ['Afrique subsaharienne'],
    langue_requise: 'Anglais',
    niveau_langue_requis: 'B2',
    age_max: null,
    nb_places: null,
    criteres: [],
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // Vider la table et réinitialiser les matches
    await client.query('DELETE FROM matches');
    await client.query('DELETE FROM scholarships');
    await client.query('ALTER SEQUENCE scholarships_id_seq RESTART WITH 1');

    for (const s of scholarships) {
      await client.query(
        `INSERT INTO scholarships (
          nom, organisme, pays, code_pays, niveau, domaine, montant,
          deadline, date_debut, duree, type_financement, description, lien,
          avantages, documents_requis, nationalites_eligibles,
          langue_requise, niveau_langue_requis, age_max, nb_places, criteres
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)`,
        [
          s.nom, s.organisme, s.pays, s.code_pays, s.niveau, s.domaine, s.montant,
          s.deadline, s.date_debut, s.duree, s.type_financement, s.description, s.lien,
          s.avantages || [], s.documents_requis || [], s.nationalites_eligibles || [],
          s.langue_requise, s.niveau_langue_requis, s.age_max || null, s.nb_places || null,
          JSON.stringify(s.criteres || []),
        ]
      );
    }

    await client.query('COMMIT');
    console.log(`✅ ${scholarships.length} bourses insérées avec succès`);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌ Erreur seed :', err.message);
    throw err;
  } finally {
    client.release();
  }
}

seed().then(() => process.exit(0)).catch(() => process.exit(1));
